version: '2'
services:
  redis:
    image: redis:alpine
  zoo1:
    image: zookeeper:latest
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zoo1:2888:3888
    volumes:
      - ./docker-data/zoo1/data:/data
      - ./docker-data/zoo1/datalog:/datalog
  cass1:
    image: cassandra:3
    environment:
      CASSANDRA_CLUSTER_NAME: v1x1_dev
    volumes:
      - ./docker-data/cassandra:/var/lib/cassandra
  chat_router:
    image: v1x1-chat_router:latest
    depends_on:
      - redis
      - zoo1
  event_router:
    image: v1x1-event_router:latest
    depends_on:
      - redis
      - zoo1
      - cass1
  tmi:
    image: v1x1-tmi:latest
    depends_on:
      - redis
      - zoo1
      - cass1
  scheduler:
    image: v1x1-scheduler:latest
    depends_on:
      - redis
      - zoo1
      - cass1
  hello_world:
    image: v1x1-hello_world:latest
    depends_on:
      - redis
      - zoo1
      - cass1
  link_purger:
    image: v1x1-link_purger:latest
    depends_on:
      - redis
      - zoo1
      - cass1
      - chat_router
  timed_messages:
    image: v1x1-timed_messages:latest
    depends_on:
      - redis
      - zoo1
      - cass1
      - chat_router
      - event_router
      - scheduler
  caster:
    image: v1x1-caster:latest
    depends_on:
      - redis
      - zoo1
      - cass1
      - chat_router
  ops_tool:
    image: v1x1-ops_tool:latest
    depends_on:
      - redis
      - zoo1
      - cass1
      - chat_router
  api:
    image: v1x1-api:latest
    depends_on:
      - redis
      - zoo1
      - cass1
  quotes:
    image: v1x1-quotes:latest
    depends_on:
      - redis
      - zoo1
      - cass1
