version: '2.1'
services:
  redis:
    image: redis:alpine
  zoo:
    image: zookeeper@sha256:50cfe2c77fe203ab528ffb808f1a8b505db73b1f85aedbc52e4fdde69e2ebfe8
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zoo:2888:3888
    volumes:
      - ${V1X1_DOCKER_DATA:-.}/docker-data/zoo/data:/data
      - ${V1X1_DOCKER_DATA:-.}/docker-data/zoo/datalog:/datalog
  cass:
    image: cassandra:3.9
    environment:
      CASSANDRA_CLUSTER_NAME: v1x1_dev
    volumes:
      - ${V1X1_DOCKER_DATA:-.}/docker-data/cassandra:/var/lib/cassandra
  chat_router:
    image: v1x1-chat_router:latest
    depends_on:
      - redis
      - zoo
  event_router:
    image: v1x1-event_router:latest
    depends_on:
      - redis
      - zoo
      - cass
  tmi:
    image: v1x1-tmi:latest
    depends_on:
      - redis
      - zoo
      - cass
  discord:
    image: v1x1-discord:latest
    depends_on:
      - redis
      - zoo
      - cass
  scheduler:
    image: v1x1-scheduler:latest
    depends_on:
      - redis
      - zoo
      - cass
  hello_world:
    image: v1x1-hello_world:latest
    depends_on:
      - redis
      - zoo
      - cass
  link_purger:
    image: v1x1-link_purger:latest
    depends_on:
      - redis
      - zoo
      - cass
      - chat_router
  timed_messages:
    image: v1x1-timed_messages:latest
    depends_on:
      - redis
      - zoo
      - cass
      - chat_router
      - event_router
      - scheduler
  caster:
    image: v1x1-caster:latest
    depends_on:
      - redis
      - zoo
      - cass
      - chat_router
  ops_tool:
    image: v1x1-ops_tool:latest
    depends_on:
      - redis
      - zoo
      - cass
      - chat_router
  api:
    image: v1x1-api:latest
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - zoo
      - cass
  quotes:
    image: v1x1-quotes:latest
    depends_on:
      - redis
      - zoo
      - cass
  factoids:
    image: v1x1-factoids:latest
    depends_on:
      - redis
      - zoo
      - cass
  uptime:
    image: v1x1-uptime:latest
    depends_on:
      - redis
      - zoo
      - cass
