// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Channel.proto

package tv.twitchbot.common.dto.proto.core;

public final class ChannelOuterClass {
  private ChannelOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ChannelOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tv.twitchbot.common.dto.proto.core.Channel)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string name = 1;</code>
     */
    boolean hasName();
    /**
     * <code>required string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>required string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>required .tv.twitchbot.common.dto.proto.core.Channel.ChannelType type = 2;</code>
     */
    boolean hasType();
    /**
     * <code>required .tv.twitchbot.common.dto.proto.core.Channel.ChannelType type = 2;</code>
     */
    tv.twitchbot.common.dto.proto.core.ChannelOuterClass.Channel.ChannelType getType();

    /**
     * <code>required .tv.twitchbot.common.dto.proto.core.Tenant tenant = 3;</code>
     */
    boolean hasTenant();
    /**
     * <code>required .tv.twitchbot.common.dto.proto.core.Tenant tenant = 3;</code>
     */
    tv.twitchbot.common.dto.proto.core.TenantOuterClass.Tenant getTenant();
    /**
     * <code>required .tv.twitchbot.common.dto.proto.core.Tenant tenant = 3;</code>
     */
    tv.twitchbot.common.dto.proto.core.TenantOuterClass.TenantOrBuilder getTenantOrBuilder();
  }
  /**
   * Protobuf type {@code tv.twitchbot.common.dto.proto.core.Channel}
   */
  public  static final class Channel extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tv.twitchbot.common.dto.proto.core.Channel)
      ChannelOrBuilder {
    // Use Channel.newBuilder() to construct.
    private Channel(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Channel() {
      name_ = "";
      type_ = 1;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Channel(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              name_ = bs;
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              tv.twitchbot.common.dto.proto.core.ChannelOuterClass.Channel.ChannelType value = tv.twitchbot.common.dto.proto.core.ChannelOuterClass.Channel.ChannelType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                type_ = rawValue;
              }
              break;
            }
            case 26: {
              tv.twitchbot.common.dto.proto.core.TenantOuterClass.Tenant.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) == 0x00000004)) {
                subBuilder = tenant_.toBuilder();
              }
              tenant_ = input.readMessage(tv.twitchbot.common.dto.proto.core.TenantOuterClass.Tenant.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(tenant_);
                tenant_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return tv.twitchbot.common.dto.proto.core.ChannelOuterClass.internal_static_tv_twitchbot_common_dto_proto_core_Channel_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return tv.twitchbot.common.dto.proto.core.ChannelOuterClass.internal_static_tv_twitchbot_common_dto_proto_core_Channel_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              tv.twitchbot.common.dto.proto.core.ChannelOuterClass.Channel.class, tv.twitchbot.common.dto.proto.core.ChannelOuterClass.Channel.Builder.class);
    }

    /**
     * Protobuf enum {@code tv.twitchbot.common.dto.proto.core.Channel.ChannelType}
     */
    public enum ChannelType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>TWITCH = 1;</code>
       */
      TWITCH(1),
      /**
       * <code>DISCORD = 2;</code>
       */
      DISCORD(2),
      ;

      /**
       * <code>TWITCH = 1;</code>
       */
      public static final int TWITCH_VALUE = 1;
      /**
       * <code>DISCORD = 2;</code>
       */
      public static final int DISCORD_VALUE = 2;


      public final int getNumber() {
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static ChannelType valueOf(int value) {
        return forNumber(value);
      }

      public static ChannelType forNumber(int value) {
        switch (value) {
          case 1: return TWITCH;
          case 2: return DISCORD;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<ChannelType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          ChannelType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<ChannelType>() {
              public ChannelType findValueByNumber(int number) {
                return ChannelType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return tv.twitchbot.common.dto.proto.core.ChannelOuterClass.Channel.getDescriptor().getEnumTypes().get(0);
      }

      private static final ChannelType[] VALUES = values();

      public static ChannelType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private ChannelType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:tv.twitchbot.common.dto.proto.core.Channel.ChannelType)
    }

    private int bitField0_;
    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>required string name = 1;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 2;
    private int type_;
    /**
     * <code>required .tv.twitchbot.common.dto.proto.core.Channel.ChannelType type = 2;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .tv.twitchbot.common.dto.proto.core.Channel.ChannelType type = 2;</code>
     */
    public tv.twitchbot.common.dto.proto.core.ChannelOuterClass.Channel.ChannelType getType() {
      tv.twitchbot.common.dto.proto.core.ChannelOuterClass.Channel.ChannelType result = tv.twitchbot.common.dto.proto.core.ChannelOuterClass.Channel.ChannelType.valueOf(type_);
      return result == null ? tv.twitchbot.common.dto.proto.core.ChannelOuterClass.Channel.ChannelType.TWITCH : result;
    }

    public static final int TENANT_FIELD_NUMBER = 3;
    private tv.twitchbot.common.dto.proto.core.TenantOuterClass.Tenant tenant_;
    /**
     * <code>required .tv.twitchbot.common.dto.proto.core.Tenant tenant = 3;</code>
     */
    public boolean hasTenant() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required .tv.twitchbot.common.dto.proto.core.Tenant tenant = 3;</code>
     */
    public tv.twitchbot.common.dto.proto.core.TenantOuterClass.Tenant getTenant() {
      return tenant_ == null ? tv.twitchbot.common.dto.proto.core.TenantOuterClass.Tenant.getDefaultInstance() : tenant_;
    }
    /**
     * <code>required .tv.twitchbot.common.dto.proto.core.Tenant tenant = 3;</code>
     */
    public tv.twitchbot.common.dto.proto.core.TenantOuterClass.TenantOrBuilder getTenantOrBuilder() {
      return tenant_ == null ? tv.twitchbot.common.dto.proto.core.TenantOuterClass.Tenant.getDefaultInstance() : tenant_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTenant()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getTenant().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, type_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, getTenant());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, type_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getTenant());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof tv.twitchbot.common.dto.proto.core.ChannelOuterClass.Channel)) {
        return super.equals(obj);
      }
      tv.twitchbot.common.dto.proto.core.ChannelOuterClass.Channel other = (tv.twitchbot.common.dto.proto.core.ChannelOuterClass.Channel) obj;

      boolean result = true;
      result = result && (hasName() == other.hasName());
      if (hasName()) {
        result = result && getName()
            .equals(other.getName());
      }
      result = result && (hasType() == other.hasType());
      if (hasType()) {
        result = result && type_ == other.type_;
      }
      result = result && (hasTenant() == other.hasTenant());
      if (hasTenant()) {
        result = result && getTenant()
            .equals(other.getTenant());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasName()) {
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
      }
      if (hasType()) {
        hash = (37 * hash) + TYPE_FIELD_NUMBER;
        hash = (53 * hash) + type_;
      }
      if (hasTenant()) {
        hash = (37 * hash) + TENANT_FIELD_NUMBER;
        hash = (53 * hash) + getTenant().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static tv.twitchbot.common.dto.proto.core.ChannelOuterClass.Channel parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tv.twitchbot.common.dto.proto.core.ChannelOuterClass.Channel parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tv.twitchbot.common.dto.proto.core.ChannelOuterClass.Channel parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tv.twitchbot.common.dto.proto.core.ChannelOuterClass.Channel parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tv.twitchbot.common.dto.proto.core.ChannelOuterClass.Channel parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static tv.twitchbot.common.dto.proto.core.ChannelOuterClass.Channel parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static tv.twitchbot.common.dto.proto.core.ChannelOuterClass.Channel parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static tv.twitchbot.common.dto.proto.core.ChannelOuterClass.Channel parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static tv.twitchbot.common.dto.proto.core.ChannelOuterClass.Channel parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static tv.twitchbot.common.dto.proto.core.ChannelOuterClass.Channel parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(tv.twitchbot.common.dto.proto.core.ChannelOuterClass.Channel prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tv.twitchbot.common.dto.proto.core.Channel}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tv.twitchbot.common.dto.proto.core.Channel)
        tv.twitchbot.common.dto.proto.core.ChannelOuterClass.ChannelOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return tv.twitchbot.common.dto.proto.core.ChannelOuterClass.internal_static_tv_twitchbot_common_dto_proto_core_Channel_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return tv.twitchbot.common.dto.proto.core.ChannelOuterClass.internal_static_tv_twitchbot_common_dto_proto_core_Channel_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                tv.twitchbot.common.dto.proto.core.ChannelOuterClass.Channel.class, tv.twitchbot.common.dto.proto.core.ChannelOuterClass.Channel.Builder.class);
      }

      // Construct using tv.twitchbot.common.dto.proto.core.ChannelOuterClass.Channel.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getTenantFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = 1;
        bitField0_ = (bitField0_ & ~0x00000002);
        if (tenantBuilder_ == null) {
          tenant_ = null;
        } else {
          tenantBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return tv.twitchbot.common.dto.proto.core.ChannelOuterClass.internal_static_tv_twitchbot_common_dto_proto_core_Channel_descriptor;
      }

      public tv.twitchbot.common.dto.proto.core.ChannelOuterClass.Channel getDefaultInstanceForType() {
        return tv.twitchbot.common.dto.proto.core.ChannelOuterClass.Channel.getDefaultInstance();
      }

      public tv.twitchbot.common.dto.proto.core.ChannelOuterClass.Channel build() {
        tv.twitchbot.common.dto.proto.core.ChannelOuterClass.Channel result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public tv.twitchbot.common.dto.proto.core.ChannelOuterClass.Channel buildPartial() {
        tv.twitchbot.common.dto.proto.core.ChannelOuterClass.Channel result = new tv.twitchbot.common.dto.proto.core.ChannelOuterClass.Channel(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (tenantBuilder_ == null) {
          result.tenant_ = tenant_;
        } else {
          result.tenant_ = tenantBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof tv.twitchbot.common.dto.proto.core.ChannelOuterClass.Channel) {
          return mergeFrom((tv.twitchbot.common.dto.proto.core.ChannelOuterClass.Channel)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(tv.twitchbot.common.dto.proto.core.ChannelOuterClass.Channel other) {
        if (other == tv.twitchbot.common.dto.proto.core.ChannelOuterClass.Channel.getDefaultInstance()) return this;
        if (other.hasName()) {
          bitField0_ |= 0x00000001;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasTenant()) {
          mergeTenant(other.getTenant());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasName()) {
          return false;
        }
        if (!hasType()) {
          return false;
        }
        if (!hasTenant()) {
          return false;
        }
        if (!getTenant().isInitialized()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        tv.twitchbot.common.dto.proto.core.ChannelOuterClass.Channel parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (tv.twitchbot.common.dto.proto.core.ChannelOuterClass.Channel) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object name_ = "";
      /**
       * <code>required string name = 1;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }

      private int type_ = 1;
      /**
       * <code>required .tv.twitchbot.common.dto.proto.core.Channel.ChannelType type = 2;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .tv.twitchbot.common.dto.proto.core.Channel.ChannelType type = 2;</code>
       */
      public tv.twitchbot.common.dto.proto.core.ChannelOuterClass.Channel.ChannelType getType() {
        tv.twitchbot.common.dto.proto.core.ChannelOuterClass.Channel.ChannelType result = tv.twitchbot.common.dto.proto.core.ChannelOuterClass.Channel.ChannelType.valueOf(type_);
        return result == null ? tv.twitchbot.common.dto.proto.core.ChannelOuterClass.Channel.ChannelType.TWITCH : result;
      }
      /**
       * <code>required .tv.twitchbot.common.dto.proto.core.Channel.ChannelType type = 2;</code>
       */
      public Builder setType(tv.twitchbot.common.dto.proto.core.ChannelOuterClass.Channel.ChannelType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>required .tv.twitchbot.common.dto.proto.core.Channel.ChannelType type = 2;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        type_ = 1;
        onChanged();
        return this;
      }

      private tv.twitchbot.common.dto.proto.core.TenantOuterClass.Tenant tenant_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          tv.twitchbot.common.dto.proto.core.TenantOuterClass.Tenant, tv.twitchbot.common.dto.proto.core.TenantOuterClass.Tenant.Builder, tv.twitchbot.common.dto.proto.core.TenantOuterClass.TenantOrBuilder> tenantBuilder_;
      /**
       * <code>required .tv.twitchbot.common.dto.proto.core.Tenant tenant = 3;</code>
       */
      public boolean hasTenant() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required .tv.twitchbot.common.dto.proto.core.Tenant tenant = 3;</code>
       */
      public tv.twitchbot.common.dto.proto.core.TenantOuterClass.Tenant getTenant() {
        if (tenantBuilder_ == null) {
          return tenant_ == null ? tv.twitchbot.common.dto.proto.core.TenantOuterClass.Tenant.getDefaultInstance() : tenant_;
        } else {
          return tenantBuilder_.getMessage();
        }
      }
      /**
       * <code>required .tv.twitchbot.common.dto.proto.core.Tenant tenant = 3;</code>
       */
      public Builder setTenant(tv.twitchbot.common.dto.proto.core.TenantOuterClass.Tenant value) {
        if (tenantBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          tenant_ = value;
          onChanged();
        } else {
          tenantBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>required .tv.twitchbot.common.dto.proto.core.Tenant tenant = 3;</code>
       */
      public Builder setTenant(
          tv.twitchbot.common.dto.proto.core.TenantOuterClass.Tenant.Builder builderForValue) {
        if (tenantBuilder_ == null) {
          tenant_ = builderForValue.build();
          onChanged();
        } else {
          tenantBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>required .tv.twitchbot.common.dto.proto.core.Tenant tenant = 3;</code>
       */
      public Builder mergeTenant(tv.twitchbot.common.dto.proto.core.TenantOuterClass.Tenant value) {
        if (tenantBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              tenant_ != null &&
              tenant_ != tv.twitchbot.common.dto.proto.core.TenantOuterClass.Tenant.getDefaultInstance()) {
            tenant_ =
              tv.twitchbot.common.dto.proto.core.TenantOuterClass.Tenant.newBuilder(tenant_).mergeFrom(value).buildPartial();
          } else {
            tenant_ = value;
          }
          onChanged();
        } else {
          tenantBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>required .tv.twitchbot.common.dto.proto.core.Tenant tenant = 3;</code>
       */
      public Builder clearTenant() {
        if (tenantBuilder_ == null) {
          tenant_ = null;
          onChanged();
        } else {
          tenantBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <code>required .tv.twitchbot.common.dto.proto.core.Tenant tenant = 3;</code>
       */
      public tv.twitchbot.common.dto.proto.core.TenantOuterClass.Tenant.Builder getTenantBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getTenantFieldBuilder().getBuilder();
      }
      /**
       * <code>required .tv.twitchbot.common.dto.proto.core.Tenant tenant = 3;</code>
       */
      public tv.twitchbot.common.dto.proto.core.TenantOuterClass.TenantOrBuilder getTenantOrBuilder() {
        if (tenantBuilder_ != null) {
          return tenantBuilder_.getMessageOrBuilder();
        } else {
          return tenant_ == null ?
              tv.twitchbot.common.dto.proto.core.TenantOuterClass.Tenant.getDefaultInstance() : tenant_;
        }
      }
      /**
       * <code>required .tv.twitchbot.common.dto.proto.core.Tenant tenant = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          tv.twitchbot.common.dto.proto.core.TenantOuterClass.Tenant, tv.twitchbot.common.dto.proto.core.TenantOuterClass.Tenant.Builder, tv.twitchbot.common.dto.proto.core.TenantOuterClass.TenantOrBuilder> 
          getTenantFieldBuilder() {
        if (tenantBuilder_ == null) {
          tenantBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              tv.twitchbot.common.dto.proto.core.TenantOuterClass.Tenant, tv.twitchbot.common.dto.proto.core.TenantOuterClass.Tenant.Builder, tv.twitchbot.common.dto.proto.core.TenantOuterClass.TenantOrBuilder>(
                  getTenant(),
                  getParentForChildren(),
                  isClean());
          tenant_ = null;
        }
        return tenantBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:tv.twitchbot.common.dto.proto.core.Channel)
    }

    // @@protoc_insertion_point(class_scope:tv.twitchbot.common.dto.proto.core.Channel)
    private static final tv.twitchbot.common.dto.proto.core.ChannelOuterClass.Channel DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new tv.twitchbot.common.dto.proto.core.ChannelOuterClass.Channel();
    }

    public static tv.twitchbot.common.dto.proto.core.ChannelOuterClass.Channel getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Channel>
        PARSER = new com.google.protobuf.AbstractParser<Channel>() {
      public Channel parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Channel(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Channel> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Channel> getParserForType() {
      return PARSER;
    }

    public tv.twitchbot.common.dto.proto.core.ChannelOuterClass.Channel getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tv_twitchbot_common_dto_proto_core_Channel_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tv_twitchbot_common_dto_proto_core_Channel_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rChannel.proto\022\"tv.twitchbot.common.dto" +
      ".proto.core\032\014Tenant.proto\"\302\001\n\007Channel\022\014\n" +
      "\004name\030\001 \002(\t\022E\n\004type\030\002 \002(\01627.tv.twitchbot" +
      ".common.dto.proto.core.Channel.ChannelTy" +
      "pe\022:\n\006tenant\030\003 \002(\0132*.tv.twitchbot.common" +
      ".dto.proto.core.Tenant\"&\n\013ChannelType\022\n\n" +
      "\006TWITCH\020\001\022\013\n\007DISCORD\020\002"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          tv.twitchbot.common.dto.proto.core.TenantOuterClass.getDescriptor(),
        }, assigner);
    internal_static_tv_twitchbot_common_dto_proto_core_Channel_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tv_twitchbot_common_dto_proto_core_Channel_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tv_twitchbot_common_dto_proto_core_Channel_descriptor,
        new java.lang.String[] { "Name", "Type", "Tenant", });
    tv.twitchbot.common.dto.proto.core.TenantOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
