// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Tenant.proto

package tv.twitchbot.common.dto.proto.core;

public final class TenantOuterClass {
  private TenantOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TenantOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tv.twitchbot.common.dto.proto.core.Tenant)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .tv.twitchbot.common.dto.proto.core.UUID id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required .tv.twitchbot.common.dto.proto.core.UUID id = 1;</code>
     */
    tv.twitchbot.common.dto.proto.core.UUIDOuterClass.UUID getId();
    /**
     * <code>required .tv.twitchbot.common.dto.proto.core.UUID id = 1;</code>
     */
    tv.twitchbot.common.dto.proto.core.UUIDOuterClass.UUIDOrBuilder getIdOrBuilder();
  }
  /**
   * Protobuf type {@code tv.twitchbot.common.dto.proto.core.Tenant}
   */
  public  static final class Tenant extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tv.twitchbot.common.dto.proto.core.Tenant)
      TenantOrBuilder {
    // Use Tenant.newBuilder() to construct.
    private Tenant(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Tenant() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Tenant(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              tv.twitchbot.common.dto.proto.core.UUIDOuterClass.UUID.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = id_.toBuilder();
              }
              id_ = input.readMessage(tv.twitchbot.common.dto.proto.core.UUIDOuterClass.UUID.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(id_);
                id_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return tv.twitchbot.common.dto.proto.core.TenantOuterClass.internal_static_tv_twitchbot_common_dto_proto_core_Tenant_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return tv.twitchbot.common.dto.proto.core.TenantOuterClass.internal_static_tv_twitchbot_common_dto_proto_core_Tenant_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              tv.twitchbot.common.dto.proto.core.TenantOuterClass.Tenant.class, tv.twitchbot.common.dto.proto.core.TenantOuterClass.Tenant.Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private tv.twitchbot.common.dto.proto.core.UUIDOuterClass.UUID id_;
    /**
     * <code>required .tv.twitchbot.common.dto.proto.core.UUID id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .tv.twitchbot.common.dto.proto.core.UUID id = 1;</code>
     */
    public tv.twitchbot.common.dto.proto.core.UUIDOuterClass.UUID getId() {
      return id_ == null ? tv.twitchbot.common.dto.proto.core.UUIDOuterClass.UUID.getDefaultInstance() : id_;
    }
    /**
     * <code>required .tv.twitchbot.common.dto.proto.core.UUID id = 1;</code>
     */
    public tv.twitchbot.common.dto.proto.core.UUIDOuterClass.UUIDOrBuilder getIdOrBuilder() {
      return id_ == null ? tv.twitchbot.common.dto.proto.core.UUIDOuterClass.UUID.getDefaultInstance() : id_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getId().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, getId());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getId());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof tv.twitchbot.common.dto.proto.core.TenantOuterClass.Tenant)) {
        return super.equals(obj);
      }
      tv.twitchbot.common.dto.proto.core.TenantOuterClass.Tenant other = (tv.twitchbot.common.dto.proto.core.TenantOuterClass.Tenant) obj;

      boolean result = true;
      result = result && (hasId() == other.hasId());
      if (hasId()) {
        result = result && getId()
            .equals(other.getId());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasId()) {
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + getId().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static tv.twitchbot.common.dto.proto.core.TenantOuterClass.Tenant parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tv.twitchbot.common.dto.proto.core.TenantOuterClass.Tenant parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tv.twitchbot.common.dto.proto.core.TenantOuterClass.Tenant parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tv.twitchbot.common.dto.proto.core.TenantOuterClass.Tenant parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tv.twitchbot.common.dto.proto.core.TenantOuterClass.Tenant parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static tv.twitchbot.common.dto.proto.core.TenantOuterClass.Tenant parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static tv.twitchbot.common.dto.proto.core.TenantOuterClass.Tenant parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static tv.twitchbot.common.dto.proto.core.TenantOuterClass.Tenant parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static tv.twitchbot.common.dto.proto.core.TenantOuterClass.Tenant parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static tv.twitchbot.common.dto.proto.core.TenantOuterClass.Tenant parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(tv.twitchbot.common.dto.proto.core.TenantOuterClass.Tenant prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tv.twitchbot.common.dto.proto.core.Tenant}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tv.twitchbot.common.dto.proto.core.Tenant)
        tv.twitchbot.common.dto.proto.core.TenantOuterClass.TenantOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return tv.twitchbot.common.dto.proto.core.TenantOuterClass.internal_static_tv_twitchbot_common_dto_proto_core_Tenant_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return tv.twitchbot.common.dto.proto.core.TenantOuterClass.internal_static_tv_twitchbot_common_dto_proto_core_Tenant_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                tv.twitchbot.common.dto.proto.core.TenantOuterClass.Tenant.class, tv.twitchbot.common.dto.proto.core.TenantOuterClass.Tenant.Builder.class);
      }

      // Construct using tv.twitchbot.common.dto.proto.core.TenantOuterClass.Tenant.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getIdFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (idBuilder_ == null) {
          id_ = null;
        } else {
          idBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return tv.twitchbot.common.dto.proto.core.TenantOuterClass.internal_static_tv_twitchbot_common_dto_proto_core_Tenant_descriptor;
      }

      public tv.twitchbot.common.dto.proto.core.TenantOuterClass.Tenant getDefaultInstanceForType() {
        return tv.twitchbot.common.dto.proto.core.TenantOuterClass.Tenant.getDefaultInstance();
      }

      public tv.twitchbot.common.dto.proto.core.TenantOuterClass.Tenant build() {
        tv.twitchbot.common.dto.proto.core.TenantOuterClass.Tenant result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public tv.twitchbot.common.dto.proto.core.TenantOuterClass.Tenant buildPartial() {
        tv.twitchbot.common.dto.proto.core.TenantOuterClass.Tenant result = new tv.twitchbot.common.dto.proto.core.TenantOuterClass.Tenant(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (idBuilder_ == null) {
          result.id_ = id_;
        } else {
          result.id_ = idBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof tv.twitchbot.common.dto.proto.core.TenantOuterClass.Tenant) {
          return mergeFrom((tv.twitchbot.common.dto.proto.core.TenantOuterClass.Tenant)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(tv.twitchbot.common.dto.proto.core.TenantOuterClass.Tenant other) {
        if (other == tv.twitchbot.common.dto.proto.core.TenantOuterClass.Tenant.getDefaultInstance()) return this;
        if (other.hasId()) {
          mergeId(other.getId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          return false;
        }
        if (!getId().isInitialized()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        tv.twitchbot.common.dto.proto.core.TenantOuterClass.Tenant parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (tv.twitchbot.common.dto.proto.core.TenantOuterClass.Tenant) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private tv.twitchbot.common.dto.proto.core.UUIDOuterClass.UUID id_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          tv.twitchbot.common.dto.proto.core.UUIDOuterClass.UUID, tv.twitchbot.common.dto.proto.core.UUIDOuterClass.UUID.Builder, tv.twitchbot.common.dto.proto.core.UUIDOuterClass.UUIDOrBuilder> idBuilder_;
      /**
       * <code>required .tv.twitchbot.common.dto.proto.core.UUID id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .tv.twitchbot.common.dto.proto.core.UUID id = 1;</code>
       */
      public tv.twitchbot.common.dto.proto.core.UUIDOuterClass.UUID getId() {
        if (idBuilder_ == null) {
          return id_ == null ? tv.twitchbot.common.dto.proto.core.UUIDOuterClass.UUID.getDefaultInstance() : id_;
        } else {
          return idBuilder_.getMessage();
        }
      }
      /**
       * <code>required .tv.twitchbot.common.dto.proto.core.UUID id = 1;</code>
       */
      public Builder setId(tv.twitchbot.common.dto.proto.core.UUIDOuterClass.UUID value) {
        if (idBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          id_ = value;
          onChanged();
        } else {
          idBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .tv.twitchbot.common.dto.proto.core.UUID id = 1;</code>
       */
      public Builder setId(
          tv.twitchbot.common.dto.proto.core.UUIDOuterClass.UUID.Builder builderForValue) {
        if (idBuilder_ == null) {
          id_ = builderForValue.build();
          onChanged();
        } else {
          idBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .tv.twitchbot.common.dto.proto.core.UUID id = 1;</code>
       */
      public Builder mergeId(tv.twitchbot.common.dto.proto.core.UUIDOuterClass.UUID value) {
        if (idBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              id_ != null &&
              id_ != tv.twitchbot.common.dto.proto.core.UUIDOuterClass.UUID.getDefaultInstance()) {
            id_ =
              tv.twitchbot.common.dto.proto.core.UUIDOuterClass.UUID.newBuilder(id_).mergeFrom(value).buildPartial();
          } else {
            id_ = value;
          }
          onChanged();
        } else {
          idBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .tv.twitchbot.common.dto.proto.core.UUID id = 1;</code>
       */
      public Builder clearId() {
        if (idBuilder_ == null) {
          id_ = null;
          onChanged();
        } else {
          idBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>required .tv.twitchbot.common.dto.proto.core.UUID id = 1;</code>
       */
      public tv.twitchbot.common.dto.proto.core.UUIDOuterClass.UUID.Builder getIdBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getIdFieldBuilder().getBuilder();
      }
      /**
       * <code>required .tv.twitchbot.common.dto.proto.core.UUID id = 1;</code>
       */
      public tv.twitchbot.common.dto.proto.core.UUIDOuterClass.UUIDOrBuilder getIdOrBuilder() {
        if (idBuilder_ != null) {
          return idBuilder_.getMessageOrBuilder();
        } else {
          return id_ == null ?
              tv.twitchbot.common.dto.proto.core.UUIDOuterClass.UUID.getDefaultInstance() : id_;
        }
      }
      /**
       * <code>required .tv.twitchbot.common.dto.proto.core.UUID id = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          tv.twitchbot.common.dto.proto.core.UUIDOuterClass.UUID, tv.twitchbot.common.dto.proto.core.UUIDOuterClass.UUID.Builder, tv.twitchbot.common.dto.proto.core.UUIDOuterClass.UUIDOrBuilder> 
          getIdFieldBuilder() {
        if (idBuilder_ == null) {
          idBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              tv.twitchbot.common.dto.proto.core.UUIDOuterClass.UUID, tv.twitchbot.common.dto.proto.core.UUIDOuterClass.UUID.Builder, tv.twitchbot.common.dto.proto.core.UUIDOuterClass.UUIDOrBuilder>(
                  getId(),
                  getParentForChildren(),
                  isClean());
          id_ = null;
        }
        return idBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:tv.twitchbot.common.dto.proto.core.Tenant)
    }

    // @@protoc_insertion_point(class_scope:tv.twitchbot.common.dto.proto.core.Tenant)
    private static final tv.twitchbot.common.dto.proto.core.TenantOuterClass.Tenant DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new tv.twitchbot.common.dto.proto.core.TenantOuterClass.Tenant();
    }

    public static tv.twitchbot.common.dto.proto.core.TenantOuterClass.Tenant getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Tenant>
        PARSER = new com.google.protobuf.AbstractParser<Tenant>() {
      public Tenant parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Tenant(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Tenant> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Tenant> getParserForType() {
      return PARSER;
    }

    public tv.twitchbot.common.dto.proto.core.TenantOuterClass.Tenant getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tv_twitchbot_common_dto_proto_core_Tenant_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tv_twitchbot_common_dto_proto_core_Tenant_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014Tenant.proto\022\"tv.twitchbot.common.dto." +
      "proto.core\032\nUUID.proto\">\n\006Tenant\0224\n\002id\030\001" +
      " \002(\0132(.tv.twitchbot.common.dto.proto.cor" +
      "e.UUID"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          tv.twitchbot.common.dto.proto.core.UUIDOuterClass.getDescriptor(),
        }, assigner);
    internal_static_tv_twitchbot_common_dto_proto_core_Tenant_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tv_twitchbot_common_dto_proto_core_Tenant_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tv_twitchbot_common_dto_proto_core_Tenant_descriptor,
        new java.lang.String[] { "Id", });
    tv.twitchbot.common.dto.proto.core.UUIDOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
