// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: User.proto

package tv.twitchbot.common.dto.proto.core;

public final class UserOuterClass {
  private UserOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface UserOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tv.twitchbot.common.dto.proto.core.User)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string name = 1;</code>
     */
    boolean hasName();
    /**
     * <code>required string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>required string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>required .tv.twitchbot.common.dto.proto.core.User.UserType type = 2;</code>
     */
    boolean hasType();
    /**
     * <code>required .tv.twitchbot.common.dto.proto.core.User.UserType type = 2;</code>
     */
    tv.twitchbot.common.dto.proto.core.UserOuterClass.User.UserType getType();

    /**
     * <code>optional string mention = 3;</code>
     */
    boolean hasMention();
    /**
     * <code>optional string mention = 3;</code>
     */
    java.lang.String getMention();
    /**
     * <code>optional string mention = 3;</code>
     */
    com.google.protobuf.ByteString
        getMentionBytes();

    /**
     * <code>repeated .tv.twitchbot.common.dto.proto.core.User.Permission permissions = 4;</code>
     */
    java.util.List<tv.twitchbot.common.dto.proto.core.UserOuterClass.User.Permission> 
        getPermissionsList();
    /**
     * <code>repeated .tv.twitchbot.common.dto.proto.core.User.Permission permissions = 4;</code>
     */
    tv.twitchbot.common.dto.proto.core.UserOuterClass.User.Permission getPermissions(int index);
    /**
     * <code>repeated .tv.twitchbot.common.dto.proto.core.User.Permission permissions = 4;</code>
     */
    int getPermissionsCount();
    /**
     * <code>repeated .tv.twitchbot.common.dto.proto.core.User.Permission permissions = 4;</code>
     */
    java.util.List<? extends tv.twitchbot.common.dto.proto.core.UserOuterClass.User.PermissionOrBuilder> 
        getPermissionsOrBuilderList();
    /**
     * <code>repeated .tv.twitchbot.common.dto.proto.core.User.Permission permissions = 4;</code>
     */
    tv.twitchbot.common.dto.proto.core.UserOuterClass.User.PermissionOrBuilder getPermissionsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code tv.twitchbot.common.dto.proto.core.User}
   */
  public  static final class User extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tv.twitchbot.common.dto.proto.core.User)
      UserOrBuilder {
    // Use User.newBuilder() to construct.
    private User(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private User() {
      name_ = "";
      type_ = 1;
      mention_ = "";
      permissions_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private User(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              name_ = bs;
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              tv.twitchbot.common.dto.proto.core.UserOuterClass.User.UserType value = tv.twitchbot.common.dto.proto.core.UserOuterClass.User.UserType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                type_ = rawValue;
              }
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              mention_ = bs;
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                permissions_ = new java.util.ArrayList<tv.twitchbot.common.dto.proto.core.UserOuterClass.User.Permission>();
                mutable_bitField0_ |= 0x00000008;
              }
              permissions_.add(
                  input.readMessage(tv.twitchbot.common.dto.proto.core.UserOuterClass.User.Permission.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          permissions_ = java.util.Collections.unmodifiableList(permissions_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return tv.twitchbot.common.dto.proto.core.UserOuterClass.internal_static_tv_twitchbot_common_dto_proto_core_User_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return tv.twitchbot.common.dto.proto.core.UserOuterClass.internal_static_tv_twitchbot_common_dto_proto_core_User_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              tv.twitchbot.common.dto.proto.core.UserOuterClass.User.class, tv.twitchbot.common.dto.proto.core.UserOuterClass.User.Builder.class);
    }

    /**
     * Protobuf enum {@code tv.twitchbot.common.dto.proto.core.User.UserType}
     */
    public enum UserType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>TWITCH = 1;</code>
       */
      TWITCH(1),
      /**
       * <code>DISCORD = 2;</code>
       */
      DISCORD(2),
      ;

      /**
       * <code>TWITCH = 1;</code>
       */
      public static final int TWITCH_VALUE = 1;
      /**
       * <code>DISCORD = 2;</code>
       */
      public static final int DISCORD_VALUE = 2;


      public final int getNumber() {
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static UserType valueOf(int value) {
        return forNumber(value);
      }

      public static UserType forNumber(int value) {
        switch (value) {
          case 1: return TWITCH;
          case 2: return DISCORD;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<UserType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          UserType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<UserType>() {
              public UserType findValueByNumber(int number) {
                return UserType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return tv.twitchbot.common.dto.proto.core.UserOuterClass.User.getDescriptor().getEnumTypes().get(0);
      }

      private static final UserType[] VALUES = values();

      public static UserType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private UserType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:tv.twitchbot.common.dto.proto.core.User.UserType)
    }

    public interface PermissionOrBuilder extends
        // @@protoc_insertion_point(interface_extends:tv.twitchbot.common.dto.proto.core.User.Permission)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>required string node = 1;</code>
       */
      boolean hasNode();
      /**
       * <code>required string node = 1;</code>
       */
      java.lang.String getNode();
      /**
       * <code>required string node = 1;</code>
       */
      com.google.protobuf.ByteString
          getNodeBytes();
    }
    /**
     * Protobuf type {@code tv.twitchbot.common.dto.proto.core.User.Permission}
     */
    public  static final class Permission extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:tv.twitchbot.common.dto.proto.core.User.Permission)
        PermissionOrBuilder {
      // Use Permission.newBuilder() to construct.
      private Permission(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Permission() {
        node_ = "";
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private Permission(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000001;
                node_ = bs;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return tv.twitchbot.common.dto.proto.core.UserOuterClass.internal_static_tv_twitchbot_common_dto_proto_core_User_Permission_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return tv.twitchbot.common.dto.proto.core.UserOuterClass.internal_static_tv_twitchbot_common_dto_proto_core_User_Permission_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                tv.twitchbot.common.dto.proto.core.UserOuterClass.User.Permission.class, tv.twitchbot.common.dto.proto.core.UserOuterClass.User.Permission.Builder.class);
      }

      private int bitField0_;
      public static final int NODE_FIELD_NUMBER = 1;
      private volatile java.lang.Object node_;
      /**
       * <code>required string node = 1;</code>
       */
      public boolean hasNode() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string node = 1;</code>
       */
      public java.lang.String getNode() {
        java.lang.Object ref = node_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            node_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string node = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNodeBytes() {
        java.lang.Object ref = node_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          node_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        if (!hasNode()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, node_);
        }
        unknownFields.writeTo(output);
      }

      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, node_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof tv.twitchbot.common.dto.proto.core.UserOuterClass.User.Permission)) {
          return super.equals(obj);
        }
        tv.twitchbot.common.dto.proto.core.UserOuterClass.User.Permission other = (tv.twitchbot.common.dto.proto.core.UserOuterClass.User.Permission) obj;

        boolean result = true;
        result = result && (hasNode() == other.hasNode());
        if (hasNode()) {
          result = result && getNode()
              .equals(other.getNode());
        }
        result = result && unknownFields.equals(other.unknownFields);
        return result;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptorForType().hashCode();
        if (hasNode()) {
          hash = (37 * hash) + NODE_FIELD_NUMBER;
          hash = (53 * hash) + getNode().hashCode();
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static tv.twitchbot.common.dto.proto.core.UserOuterClass.User.Permission parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static tv.twitchbot.common.dto.proto.core.UserOuterClass.User.Permission parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static tv.twitchbot.common.dto.proto.core.UserOuterClass.User.Permission parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static tv.twitchbot.common.dto.proto.core.UserOuterClass.User.Permission parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static tv.twitchbot.common.dto.proto.core.UserOuterClass.User.Permission parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static tv.twitchbot.common.dto.proto.core.UserOuterClass.User.Permission parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static tv.twitchbot.common.dto.proto.core.UserOuterClass.User.Permission parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static tv.twitchbot.common.dto.proto.core.UserOuterClass.User.Permission parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static tv.twitchbot.common.dto.proto.core.UserOuterClass.User.Permission parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static tv.twitchbot.common.dto.proto.core.UserOuterClass.User.Permission parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(tv.twitchbot.common.dto.proto.core.UserOuterClass.User.Permission prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code tv.twitchbot.common.dto.proto.core.User.Permission}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:tv.twitchbot.common.dto.proto.core.User.Permission)
          tv.twitchbot.common.dto.proto.core.UserOuterClass.User.PermissionOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return tv.twitchbot.common.dto.proto.core.UserOuterClass.internal_static_tv_twitchbot_common_dto_proto_core_User_Permission_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return tv.twitchbot.common.dto.proto.core.UserOuterClass.internal_static_tv_twitchbot_common_dto_proto_core_User_Permission_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  tv.twitchbot.common.dto.proto.core.UserOuterClass.User.Permission.class, tv.twitchbot.common.dto.proto.core.UserOuterClass.User.Permission.Builder.class);
        }

        // Construct using tv.twitchbot.common.dto.proto.core.UserOuterClass.User.Permission.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        public Builder clear() {
          super.clear();
          node_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return tv.twitchbot.common.dto.proto.core.UserOuterClass.internal_static_tv_twitchbot_common_dto_proto_core_User_Permission_descriptor;
        }

        public tv.twitchbot.common.dto.proto.core.UserOuterClass.User.Permission getDefaultInstanceForType() {
          return tv.twitchbot.common.dto.proto.core.UserOuterClass.User.Permission.getDefaultInstance();
        }

        public tv.twitchbot.common.dto.proto.core.UserOuterClass.User.Permission build() {
          tv.twitchbot.common.dto.proto.core.UserOuterClass.User.Permission result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public tv.twitchbot.common.dto.proto.core.UserOuterClass.User.Permission buildPartial() {
          tv.twitchbot.common.dto.proto.core.UserOuterClass.User.Permission result = new tv.twitchbot.common.dto.proto.core.UserOuterClass.User.Permission(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.node_ = node_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder clone() {
          return (Builder) super.clone();
        }
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.setField(field, value);
        }
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof tv.twitchbot.common.dto.proto.core.UserOuterClass.User.Permission) {
            return mergeFrom((tv.twitchbot.common.dto.proto.core.UserOuterClass.User.Permission)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(tv.twitchbot.common.dto.proto.core.UserOuterClass.User.Permission other) {
          if (other == tv.twitchbot.common.dto.proto.core.UserOuterClass.User.Permission.getDefaultInstance()) return this;
          if (other.hasNode()) {
            bitField0_ |= 0x00000001;
            node_ = other.node_;
            onChanged();
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        public final boolean isInitialized() {
          if (!hasNode()) {
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          tv.twitchbot.common.dto.proto.core.UserOuterClass.User.Permission parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (tv.twitchbot.common.dto.proto.core.UserOuterClass.User.Permission) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private java.lang.Object node_ = "";
        /**
         * <code>required string node = 1;</code>
         */
        public boolean hasNode() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required string node = 1;</code>
         */
        public java.lang.String getNode() {
          java.lang.Object ref = node_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              node_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string node = 1;</code>
         */
        public com.google.protobuf.ByteString
            getNodeBytes() {
          java.lang.Object ref = node_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            node_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string node = 1;</code>
         */
        public Builder setNode(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          node_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string node = 1;</code>
         */
        public Builder clearNode() {
          bitField0_ = (bitField0_ & ~0x00000001);
          node_ = getDefaultInstance().getNode();
          onChanged();
          return this;
        }
        /**
         * <code>required string node = 1;</code>
         */
        public Builder setNodeBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          node_ = value;
          onChanged();
          return this;
        }
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:tv.twitchbot.common.dto.proto.core.User.Permission)
      }

      // @@protoc_insertion_point(class_scope:tv.twitchbot.common.dto.proto.core.User.Permission)
      private static final tv.twitchbot.common.dto.proto.core.UserOuterClass.User.Permission DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new tv.twitchbot.common.dto.proto.core.UserOuterClass.User.Permission();
      }

      public static tv.twitchbot.common.dto.proto.core.UserOuterClass.User.Permission getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      @java.lang.Deprecated public static final com.google.protobuf.Parser<Permission>
          PARSER = new com.google.protobuf.AbstractParser<Permission>() {
        public Permission parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return new Permission(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<Permission> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<Permission> getParserForType() {
        return PARSER;
      }

      public tv.twitchbot.common.dto.proto.core.UserOuterClass.User.Permission getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private int bitField0_;
    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>required string name = 1;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 2;
    private int type_;
    /**
     * <code>required .tv.twitchbot.common.dto.proto.core.User.UserType type = 2;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .tv.twitchbot.common.dto.proto.core.User.UserType type = 2;</code>
     */
    public tv.twitchbot.common.dto.proto.core.UserOuterClass.User.UserType getType() {
      tv.twitchbot.common.dto.proto.core.UserOuterClass.User.UserType result = tv.twitchbot.common.dto.proto.core.UserOuterClass.User.UserType.valueOf(type_);
      return result == null ? tv.twitchbot.common.dto.proto.core.UserOuterClass.User.UserType.TWITCH : result;
    }

    public static final int MENTION_FIELD_NUMBER = 3;
    private volatile java.lang.Object mention_;
    /**
     * <code>optional string mention = 3;</code>
     */
    public boolean hasMention() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string mention = 3;</code>
     */
    public java.lang.String getMention() {
      java.lang.Object ref = mention_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          mention_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string mention = 3;</code>
     */
    public com.google.protobuf.ByteString
        getMentionBytes() {
      java.lang.Object ref = mention_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mention_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PERMISSIONS_FIELD_NUMBER = 4;
    private java.util.List<tv.twitchbot.common.dto.proto.core.UserOuterClass.User.Permission> permissions_;
    /**
     * <code>repeated .tv.twitchbot.common.dto.proto.core.User.Permission permissions = 4;</code>
     */
    public java.util.List<tv.twitchbot.common.dto.proto.core.UserOuterClass.User.Permission> getPermissionsList() {
      return permissions_;
    }
    /**
     * <code>repeated .tv.twitchbot.common.dto.proto.core.User.Permission permissions = 4;</code>
     */
    public java.util.List<? extends tv.twitchbot.common.dto.proto.core.UserOuterClass.User.PermissionOrBuilder> 
        getPermissionsOrBuilderList() {
      return permissions_;
    }
    /**
     * <code>repeated .tv.twitchbot.common.dto.proto.core.User.Permission permissions = 4;</code>
     */
    public int getPermissionsCount() {
      return permissions_.size();
    }
    /**
     * <code>repeated .tv.twitchbot.common.dto.proto.core.User.Permission permissions = 4;</code>
     */
    public tv.twitchbot.common.dto.proto.core.UserOuterClass.User.Permission getPermissions(int index) {
      return permissions_.get(index);
    }
    /**
     * <code>repeated .tv.twitchbot.common.dto.proto.core.User.Permission permissions = 4;</code>
     */
    public tv.twitchbot.common.dto.proto.core.UserOuterClass.User.PermissionOrBuilder getPermissionsOrBuilder(
        int index) {
      return permissions_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getPermissionsCount(); i++) {
        if (!getPermissions(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, type_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, mention_);
      }
      for (int i = 0; i < permissions_.size(); i++) {
        output.writeMessage(4, permissions_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, type_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, mention_);
      }
      for (int i = 0; i < permissions_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, permissions_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof tv.twitchbot.common.dto.proto.core.UserOuterClass.User)) {
        return super.equals(obj);
      }
      tv.twitchbot.common.dto.proto.core.UserOuterClass.User other = (tv.twitchbot.common.dto.proto.core.UserOuterClass.User) obj;

      boolean result = true;
      result = result && (hasName() == other.hasName());
      if (hasName()) {
        result = result && getName()
            .equals(other.getName());
      }
      result = result && (hasType() == other.hasType());
      if (hasType()) {
        result = result && type_ == other.type_;
      }
      result = result && (hasMention() == other.hasMention());
      if (hasMention()) {
        result = result && getMention()
            .equals(other.getMention());
      }
      result = result && getPermissionsList()
          .equals(other.getPermissionsList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasName()) {
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
      }
      if (hasType()) {
        hash = (37 * hash) + TYPE_FIELD_NUMBER;
        hash = (53 * hash) + type_;
      }
      if (hasMention()) {
        hash = (37 * hash) + MENTION_FIELD_NUMBER;
        hash = (53 * hash) + getMention().hashCode();
      }
      if (getPermissionsCount() > 0) {
        hash = (37 * hash) + PERMISSIONS_FIELD_NUMBER;
        hash = (53 * hash) + getPermissionsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static tv.twitchbot.common.dto.proto.core.UserOuterClass.User parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tv.twitchbot.common.dto.proto.core.UserOuterClass.User parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tv.twitchbot.common.dto.proto.core.UserOuterClass.User parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tv.twitchbot.common.dto.proto.core.UserOuterClass.User parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tv.twitchbot.common.dto.proto.core.UserOuterClass.User parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static tv.twitchbot.common.dto.proto.core.UserOuterClass.User parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static tv.twitchbot.common.dto.proto.core.UserOuterClass.User parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static tv.twitchbot.common.dto.proto.core.UserOuterClass.User parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static tv.twitchbot.common.dto.proto.core.UserOuterClass.User parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static tv.twitchbot.common.dto.proto.core.UserOuterClass.User parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(tv.twitchbot.common.dto.proto.core.UserOuterClass.User prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tv.twitchbot.common.dto.proto.core.User}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tv.twitchbot.common.dto.proto.core.User)
        tv.twitchbot.common.dto.proto.core.UserOuterClass.UserOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return tv.twitchbot.common.dto.proto.core.UserOuterClass.internal_static_tv_twitchbot_common_dto_proto_core_User_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return tv.twitchbot.common.dto.proto.core.UserOuterClass.internal_static_tv_twitchbot_common_dto_proto_core_User_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                tv.twitchbot.common.dto.proto.core.UserOuterClass.User.class, tv.twitchbot.common.dto.proto.core.UserOuterClass.User.Builder.class);
      }

      // Construct using tv.twitchbot.common.dto.proto.core.UserOuterClass.User.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getPermissionsFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = 1;
        bitField0_ = (bitField0_ & ~0x00000002);
        mention_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        if (permissionsBuilder_ == null) {
          permissions_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          permissionsBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return tv.twitchbot.common.dto.proto.core.UserOuterClass.internal_static_tv_twitchbot_common_dto_proto_core_User_descriptor;
      }

      public tv.twitchbot.common.dto.proto.core.UserOuterClass.User getDefaultInstanceForType() {
        return tv.twitchbot.common.dto.proto.core.UserOuterClass.User.getDefaultInstance();
      }

      public tv.twitchbot.common.dto.proto.core.UserOuterClass.User build() {
        tv.twitchbot.common.dto.proto.core.UserOuterClass.User result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public tv.twitchbot.common.dto.proto.core.UserOuterClass.User buildPartial() {
        tv.twitchbot.common.dto.proto.core.UserOuterClass.User result = new tv.twitchbot.common.dto.proto.core.UserOuterClass.User(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.mention_ = mention_;
        if (permissionsBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008)) {
            permissions_ = java.util.Collections.unmodifiableList(permissions_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.permissions_ = permissions_;
        } else {
          result.permissions_ = permissionsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof tv.twitchbot.common.dto.proto.core.UserOuterClass.User) {
          return mergeFrom((tv.twitchbot.common.dto.proto.core.UserOuterClass.User)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(tv.twitchbot.common.dto.proto.core.UserOuterClass.User other) {
        if (other == tv.twitchbot.common.dto.proto.core.UserOuterClass.User.getDefaultInstance()) return this;
        if (other.hasName()) {
          bitField0_ |= 0x00000001;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasMention()) {
          bitField0_ |= 0x00000004;
          mention_ = other.mention_;
          onChanged();
        }
        if (permissionsBuilder_ == null) {
          if (!other.permissions_.isEmpty()) {
            if (permissions_.isEmpty()) {
              permissions_ = other.permissions_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensurePermissionsIsMutable();
              permissions_.addAll(other.permissions_);
            }
            onChanged();
          }
        } else {
          if (!other.permissions_.isEmpty()) {
            if (permissionsBuilder_.isEmpty()) {
              permissionsBuilder_.dispose();
              permissionsBuilder_ = null;
              permissions_ = other.permissions_;
              bitField0_ = (bitField0_ & ~0x00000008);
              permissionsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getPermissionsFieldBuilder() : null;
            } else {
              permissionsBuilder_.addAllMessages(other.permissions_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasName()) {
          return false;
        }
        if (!hasType()) {
          return false;
        }
        for (int i = 0; i < getPermissionsCount(); i++) {
          if (!getPermissions(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        tv.twitchbot.common.dto.proto.core.UserOuterClass.User parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (tv.twitchbot.common.dto.proto.core.UserOuterClass.User) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object name_ = "";
      /**
       * <code>required string name = 1;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }

      private int type_ = 1;
      /**
       * <code>required .tv.twitchbot.common.dto.proto.core.User.UserType type = 2;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .tv.twitchbot.common.dto.proto.core.User.UserType type = 2;</code>
       */
      public tv.twitchbot.common.dto.proto.core.UserOuterClass.User.UserType getType() {
        tv.twitchbot.common.dto.proto.core.UserOuterClass.User.UserType result = tv.twitchbot.common.dto.proto.core.UserOuterClass.User.UserType.valueOf(type_);
        return result == null ? tv.twitchbot.common.dto.proto.core.UserOuterClass.User.UserType.TWITCH : result;
      }
      /**
       * <code>required .tv.twitchbot.common.dto.proto.core.User.UserType type = 2;</code>
       */
      public Builder setType(tv.twitchbot.common.dto.proto.core.UserOuterClass.User.UserType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>required .tv.twitchbot.common.dto.proto.core.User.UserType type = 2;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        type_ = 1;
        onChanged();
        return this;
      }

      private java.lang.Object mention_ = "";
      /**
       * <code>optional string mention = 3;</code>
       */
      public boolean hasMention() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string mention = 3;</code>
       */
      public java.lang.String getMention() {
        java.lang.Object ref = mention_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            mention_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string mention = 3;</code>
       */
      public com.google.protobuf.ByteString
          getMentionBytes() {
        java.lang.Object ref = mention_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          mention_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string mention = 3;</code>
       */
      public Builder setMention(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        mention_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string mention = 3;</code>
       */
      public Builder clearMention() {
        bitField0_ = (bitField0_ & ~0x00000004);
        mention_ = getDefaultInstance().getMention();
        onChanged();
        return this;
      }
      /**
       * <code>optional string mention = 3;</code>
       */
      public Builder setMentionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        mention_ = value;
        onChanged();
        return this;
      }

      private java.util.List<tv.twitchbot.common.dto.proto.core.UserOuterClass.User.Permission> permissions_ =
        java.util.Collections.emptyList();
      private void ensurePermissionsIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          permissions_ = new java.util.ArrayList<tv.twitchbot.common.dto.proto.core.UserOuterClass.User.Permission>(permissions_);
          bitField0_ |= 0x00000008;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          tv.twitchbot.common.dto.proto.core.UserOuterClass.User.Permission, tv.twitchbot.common.dto.proto.core.UserOuterClass.User.Permission.Builder, tv.twitchbot.common.dto.proto.core.UserOuterClass.User.PermissionOrBuilder> permissionsBuilder_;

      /**
       * <code>repeated .tv.twitchbot.common.dto.proto.core.User.Permission permissions = 4;</code>
       */
      public java.util.List<tv.twitchbot.common.dto.proto.core.UserOuterClass.User.Permission> getPermissionsList() {
        if (permissionsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(permissions_);
        } else {
          return permissionsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .tv.twitchbot.common.dto.proto.core.User.Permission permissions = 4;</code>
       */
      public int getPermissionsCount() {
        if (permissionsBuilder_ == null) {
          return permissions_.size();
        } else {
          return permissionsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .tv.twitchbot.common.dto.proto.core.User.Permission permissions = 4;</code>
       */
      public tv.twitchbot.common.dto.proto.core.UserOuterClass.User.Permission getPermissions(int index) {
        if (permissionsBuilder_ == null) {
          return permissions_.get(index);
        } else {
          return permissionsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .tv.twitchbot.common.dto.proto.core.User.Permission permissions = 4;</code>
       */
      public Builder setPermissions(
          int index, tv.twitchbot.common.dto.proto.core.UserOuterClass.User.Permission value) {
        if (permissionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePermissionsIsMutable();
          permissions_.set(index, value);
          onChanged();
        } else {
          permissionsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .tv.twitchbot.common.dto.proto.core.User.Permission permissions = 4;</code>
       */
      public Builder setPermissions(
          int index, tv.twitchbot.common.dto.proto.core.UserOuterClass.User.Permission.Builder builderForValue) {
        if (permissionsBuilder_ == null) {
          ensurePermissionsIsMutable();
          permissions_.set(index, builderForValue.build());
          onChanged();
        } else {
          permissionsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .tv.twitchbot.common.dto.proto.core.User.Permission permissions = 4;</code>
       */
      public Builder addPermissions(tv.twitchbot.common.dto.proto.core.UserOuterClass.User.Permission value) {
        if (permissionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePermissionsIsMutable();
          permissions_.add(value);
          onChanged();
        } else {
          permissionsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .tv.twitchbot.common.dto.proto.core.User.Permission permissions = 4;</code>
       */
      public Builder addPermissions(
          int index, tv.twitchbot.common.dto.proto.core.UserOuterClass.User.Permission value) {
        if (permissionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePermissionsIsMutable();
          permissions_.add(index, value);
          onChanged();
        } else {
          permissionsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .tv.twitchbot.common.dto.proto.core.User.Permission permissions = 4;</code>
       */
      public Builder addPermissions(
          tv.twitchbot.common.dto.proto.core.UserOuterClass.User.Permission.Builder builderForValue) {
        if (permissionsBuilder_ == null) {
          ensurePermissionsIsMutable();
          permissions_.add(builderForValue.build());
          onChanged();
        } else {
          permissionsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .tv.twitchbot.common.dto.proto.core.User.Permission permissions = 4;</code>
       */
      public Builder addPermissions(
          int index, tv.twitchbot.common.dto.proto.core.UserOuterClass.User.Permission.Builder builderForValue) {
        if (permissionsBuilder_ == null) {
          ensurePermissionsIsMutable();
          permissions_.add(index, builderForValue.build());
          onChanged();
        } else {
          permissionsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .tv.twitchbot.common.dto.proto.core.User.Permission permissions = 4;</code>
       */
      public Builder addAllPermissions(
          java.lang.Iterable<? extends tv.twitchbot.common.dto.proto.core.UserOuterClass.User.Permission> values) {
        if (permissionsBuilder_ == null) {
          ensurePermissionsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, permissions_);
          onChanged();
        } else {
          permissionsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .tv.twitchbot.common.dto.proto.core.User.Permission permissions = 4;</code>
       */
      public Builder clearPermissions() {
        if (permissionsBuilder_ == null) {
          permissions_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          permissionsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .tv.twitchbot.common.dto.proto.core.User.Permission permissions = 4;</code>
       */
      public Builder removePermissions(int index) {
        if (permissionsBuilder_ == null) {
          ensurePermissionsIsMutable();
          permissions_.remove(index);
          onChanged();
        } else {
          permissionsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .tv.twitchbot.common.dto.proto.core.User.Permission permissions = 4;</code>
       */
      public tv.twitchbot.common.dto.proto.core.UserOuterClass.User.Permission.Builder getPermissionsBuilder(
          int index) {
        return getPermissionsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .tv.twitchbot.common.dto.proto.core.User.Permission permissions = 4;</code>
       */
      public tv.twitchbot.common.dto.proto.core.UserOuterClass.User.PermissionOrBuilder getPermissionsOrBuilder(
          int index) {
        if (permissionsBuilder_ == null) {
          return permissions_.get(index);  } else {
          return permissionsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .tv.twitchbot.common.dto.proto.core.User.Permission permissions = 4;</code>
       */
      public java.util.List<? extends tv.twitchbot.common.dto.proto.core.UserOuterClass.User.PermissionOrBuilder> 
           getPermissionsOrBuilderList() {
        if (permissionsBuilder_ != null) {
          return permissionsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(permissions_);
        }
      }
      /**
       * <code>repeated .tv.twitchbot.common.dto.proto.core.User.Permission permissions = 4;</code>
       */
      public tv.twitchbot.common.dto.proto.core.UserOuterClass.User.Permission.Builder addPermissionsBuilder() {
        return getPermissionsFieldBuilder().addBuilder(
            tv.twitchbot.common.dto.proto.core.UserOuterClass.User.Permission.getDefaultInstance());
      }
      /**
       * <code>repeated .tv.twitchbot.common.dto.proto.core.User.Permission permissions = 4;</code>
       */
      public tv.twitchbot.common.dto.proto.core.UserOuterClass.User.Permission.Builder addPermissionsBuilder(
          int index) {
        return getPermissionsFieldBuilder().addBuilder(
            index, tv.twitchbot.common.dto.proto.core.UserOuterClass.User.Permission.getDefaultInstance());
      }
      /**
       * <code>repeated .tv.twitchbot.common.dto.proto.core.User.Permission permissions = 4;</code>
       */
      public java.util.List<tv.twitchbot.common.dto.proto.core.UserOuterClass.User.Permission.Builder> 
           getPermissionsBuilderList() {
        return getPermissionsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          tv.twitchbot.common.dto.proto.core.UserOuterClass.User.Permission, tv.twitchbot.common.dto.proto.core.UserOuterClass.User.Permission.Builder, tv.twitchbot.common.dto.proto.core.UserOuterClass.User.PermissionOrBuilder> 
          getPermissionsFieldBuilder() {
        if (permissionsBuilder_ == null) {
          permissionsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              tv.twitchbot.common.dto.proto.core.UserOuterClass.User.Permission, tv.twitchbot.common.dto.proto.core.UserOuterClass.User.Permission.Builder, tv.twitchbot.common.dto.proto.core.UserOuterClass.User.PermissionOrBuilder>(
                  permissions_,
                  ((bitField0_ & 0x00000008) == 0x00000008),
                  getParentForChildren(),
                  isClean());
          permissions_ = null;
        }
        return permissionsBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:tv.twitchbot.common.dto.proto.core.User)
    }

    // @@protoc_insertion_point(class_scope:tv.twitchbot.common.dto.proto.core.User)
    private static final tv.twitchbot.common.dto.proto.core.UserOuterClass.User DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new tv.twitchbot.common.dto.proto.core.UserOuterClass.User();
    }

    public static tv.twitchbot.common.dto.proto.core.UserOuterClass.User getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<User>
        PARSER = new com.google.protobuf.AbstractParser<User>() {
      public User parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new User(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<User> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<User> getParserForType() {
      return PARSER;
    }

    public tv.twitchbot.common.dto.proto.core.UserOuterClass.User getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tv_twitchbot_common_dto_proto_core_User_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tv_twitchbot_common_dto_proto_core_User_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tv_twitchbot_common_dto_proto_core_User_Permission_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tv_twitchbot_common_dto_proto_core_User_Permission_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nUser.proto\022\"tv.twitchbot.common.dto.pr" +
      "oto.core\"\361\001\n\004User\022\014\n\004name\030\001 \002(\t\022?\n\004type\030" +
      "\002 \002(\01621.tv.twitchbot.common.dto.proto.co" +
      "re.User.UserType\022\017\n\007mention\030\003 \001(\t\022H\n\013per" +
      "missions\030\004 \003(\01323.tv.twitchbot.common.dto" +
      ".proto.core.User.Permission\032\032\n\nPermissio" +
      "n\022\014\n\004node\030\001 \002(\t\"#\n\010UserType\022\n\n\006TWITCH\020\001\022" +
      "\013\n\007DISCORD\020\002"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_tv_twitchbot_common_dto_proto_core_User_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tv_twitchbot_common_dto_proto_core_User_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tv_twitchbot_common_dto_proto_core_User_descriptor,
        new java.lang.String[] { "Name", "Type", "Mention", "Permissions", });
    internal_static_tv_twitchbot_common_dto_proto_core_User_Permission_descriptor =
      internal_static_tv_twitchbot_common_dto_proto_core_User_descriptor.getNestedTypes().get(0);
    internal_static_tv_twitchbot_common_dto_proto_core_User_Permission_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tv_twitchbot_common_dto_proto_core_User_Permission_descriptor,
        new java.lang.String[] { "Node", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
