# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build-java:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
      MAVEN_OPTS: -Xmx3200m
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "pom.xml" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: mvn dependency:go-offline || true
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
      - run: mvn integration-test
  build-web:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "v1x1-web/package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: (cd v1x1-web; npm install)
      - save_cache:
          paths:
          - v1x1-web/node_modules
          key: v1-dependencies-{{ checksum "v1x1-web/package.json" }}
      - run:
          command: (cd v1x1-web; npm run build)
          no_output_timeout: "30m"

workflows:
  version: 2
  build:
    jobs:
    - build-java
    - build-web
