// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Bot.proto

package tv.v1x1.common.dto.proto.core;

public final class BotOuterClass {
  private BotOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
    registry.add(tv.v1x1.common.dto.proto.core.BotOuterClass.TwitchBot.data);
    registry.add(tv.v1x1.common.dto.proto.core.BotOuterClass.DiscordBot.data);
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface BotOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tv.v1x1.common.dto.proto.core.Bot)
      com.google.protobuf.GeneratedMessageV3.
          ExtendableMessageOrBuilder<Bot> {

    /**
     * <code>required string name = 1;</code>
     */
    boolean hasName();
    /**
     * <code>required string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>required string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>required .tv.v1x1.common.dto.proto.core.Platform type = 2;</code>
     */
    boolean hasType();
    /**
     * <code>required .tv.v1x1.common.dto.proto.core.Platform type = 2;</code>
     */
    tv.v1x1.common.dto.proto.core.PlatformOuterClass.Platform getType();
  }
  /**
   * Protobuf type {@code tv.v1x1.common.dto.proto.core.Bot}
   */
  public  static final class Bot extends
      com.google.protobuf.GeneratedMessageV3.ExtendableMessage<
        Bot> implements
      // @@protoc_insertion_point(message_implements:tv.v1x1.common.dto.proto.core.Bot)
      BotOrBuilder {
    // Use Bot.newBuilder() to construct.
    private Bot(com.google.protobuf.GeneratedMessageV3.ExtendableBuilder<tv.v1x1.common.dto.proto.core.BotOuterClass.Bot, ?> builder) {
      super(builder);
    }
    private Bot() {
      name_ = "";
      type_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Bot(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              name_ = bs;
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              tv.v1x1.common.dto.proto.core.PlatformOuterClass.Platform value = tv.v1x1.common.dto.proto.core.PlatformOuterClass.Platform.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                type_ = rawValue;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return tv.v1x1.common.dto.proto.core.BotOuterClass.internal_static_tv_v1x1_common_dto_proto_core_Bot_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return tv.v1x1.common.dto.proto.core.BotOuterClass.internal_static_tv_v1x1_common_dto_proto_core_Bot_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              tv.v1x1.common.dto.proto.core.BotOuterClass.Bot.class, tv.v1x1.common.dto.proto.core.BotOuterClass.Bot.Builder.class);
    }

    private int bitField0_;
    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>required string name = 1;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 2;
    private int type_;
    /**
     * <code>required .tv.v1x1.common.dto.proto.core.Platform type = 2;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .tv.v1x1.common.dto.proto.core.Platform type = 2;</code>
     */
    public tv.v1x1.common.dto.proto.core.PlatformOuterClass.Platform getType() {
      tv.v1x1.common.dto.proto.core.PlatformOuterClass.Platform result = tv.v1x1.common.dto.proto.core.PlatformOuterClass.Platform.valueOf(type_);
      return result == null ? tv.v1x1.common.dto.proto.core.PlatformOuterClass.Platform.UNKNOWN : result;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!extensionsAreInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      com.google.protobuf.GeneratedMessageV3
        .ExtendableMessage<tv.v1x1.common.dto.proto.core.BotOuterClass.Bot>.ExtensionWriter
          extensionWriter = newExtensionWriter();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, type_);
      }
      extensionWriter.writeUntil(536870912, output);
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, type_);
      }
      size += extensionsSerializedSize();
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof tv.v1x1.common.dto.proto.core.BotOuterClass.Bot)) {
        return super.equals(obj);
      }
      tv.v1x1.common.dto.proto.core.BotOuterClass.Bot other = (tv.v1x1.common.dto.proto.core.BotOuterClass.Bot) obj;

      boolean result = true;
      result = result && (hasName() == other.hasName());
      if (hasName()) {
        result = result && getName()
            .equals(other.getName());
      }
      result = result && (hasType() == other.hasType());
      if (hasType()) {
        result = result && type_ == other.type_;
      }
      result = result && unknownFields.equals(other.unknownFields);
      result = result &&
          getExtensionFields().equals(other.getExtensionFields());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasName()) {
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
      }
      if (hasType()) {
        hash = (37 * hash) + TYPE_FIELD_NUMBER;
        hash = (53 * hash) + type_;
      }
      hash = hashFields(hash, getExtensionFields());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static tv.v1x1.common.dto.proto.core.BotOuterClass.Bot parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tv.v1x1.common.dto.proto.core.BotOuterClass.Bot parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tv.v1x1.common.dto.proto.core.BotOuterClass.Bot parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tv.v1x1.common.dto.proto.core.BotOuterClass.Bot parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tv.v1x1.common.dto.proto.core.BotOuterClass.Bot parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static tv.v1x1.common.dto.proto.core.BotOuterClass.Bot parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static tv.v1x1.common.dto.proto.core.BotOuterClass.Bot parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static tv.v1x1.common.dto.proto.core.BotOuterClass.Bot parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static tv.v1x1.common.dto.proto.core.BotOuterClass.Bot parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static tv.v1x1.common.dto.proto.core.BotOuterClass.Bot parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(tv.v1x1.common.dto.proto.core.BotOuterClass.Bot prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tv.v1x1.common.dto.proto.core.Bot}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.ExtendableBuilder<
          tv.v1x1.common.dto.proto.core.BotOuterClass.Bot, Builder> implements
        // @@protoc_insertion_point(builder_implements:tv.v1x1.common.dto.proto.core.Bot)
        tv.v1x1.common.dto.proto.core.BotOuterClass.BotOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return tv.v1x1.common.dto.proto.core.BotOuterClass.internal_static_tv_v1x1_common_dto_proto_core_Bot_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return tv.v1x1.common.dto.proto.core.BotOuterClass.internal_static_tv_v1x1_common_dto_proto_core_Bot_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                tv.v1x1.common.dto.proto.core.BotOuterClass.Bot.class, tv.v1x1.common.dto.proto.core.BotOuterClass.Bot.Builder.class);
      }

      // Construct using tv.v1x1.common.dto.proto.core.BotOuterClass.Bot.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return tv.v1x1.common.dto.proto.core.BotOuterClass.internal_static_tv_v1x1_common_dto_proto_core_Bot_descriptor;
      }

      public tv.v1x1.common.dto.proto.core.BotOuterClass.Bot getDefaultInstanceForType() {
        return tv.v1x1.common.dto.proto.core.BotOuterClass.Bot.getDefaultInstance();
      }

      public tv.v1x1.common.dto.proto.core.BotOuterClass.Bot build() {
        tv.v1x1.common.dto.proto.core.BotOuterClass.Bot result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public tv.v1x1.common.dto.proto.core.BotOuterClass.Bot buildPartial() {
        tv.v1x1.common.dto.proto.core.BotOuterClass.Bot result = new tv.v1x1.common.dto.proto.core.BotOuterClass.Bot(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.type_ = type_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public <Type> Builder setExtension(
          com.google.protobuf.GeneratedMessage.GeneratedExtension<
              tv.v1x1.common.dto.proto.core.BotOuterClass.Bot, Type> extension,
          Type value) {
        return (Builder) super.setExtension(extension, value);
      }
      public <Type> Builder setExtension(
          com.google.protobuf.GeneratedMessage.GeneratedExtension<
              tv.v1x1.common.dto.proto.core.BotOuterClass.Bot, java.util.List<Type>> extension,
          int index, Type value) {
        return (Builder) super.setExtension(extension, index, value);
      }
      public <Type> Builder addExtension(
          com.google.protobuf.GeneratedMessage.GeneratedExtension<
              tv.v1x1.common.dto.proto.core.BotOuterClass.Bot, java.util.List<Type>> extension,
          Type value) {
        return (Builder) super.addExtension(extension, value);
      }
      public <Type> Builder clearExtension(
          com.google.protobuf.GeneratedMessage.GeneratedExtension<
              tv.v1x1.common.dto.proto.core.BotOuterClass.Bot, ?> extension) {
        return (Builder) super.clearExtension(extension);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof tv.v1x1.common.dto.proto.core.BotOuterClass.Bot) {
          return mergeFrom((tv.v1x1.common.dto.proto.core.BotOuterClass.Bot)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(tv.v1x1.common.dto.proto.core.BotOuterClass.Bot other) {
        if (other == tv.v1x1.common.dto.proto.core.BotOuterClass.Bot.getDefaultInstance()) return this;
        if (other.hasName()) {
          bitField0_ |= 0x00000001;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        this.mergeExtensionFields(other);
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasName()) {
          return false;
        }
        if (!hasType()) {
          return false;
        }
        if (!extensionsAreInitialized()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        tv.v1x1.common.dto.proto.core.BotOuterClass.Bot parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (tv.v1x1.common.dto.proto.core.BotOuterClass.Bot) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object name_ = "";
      /**
       * <code>required string name = 1;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }

      private int type_ = 0;
      /**
       * <code>required .tv.v1x1.common.dto.proto.core.Platform type = 2;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .tv.v1x1.common.dto.proto.core.Platform type = 2;</code>
       */
      public tv.v1x1.common.dto.proto.core.PlatformOuterClass.Platform getType() {
        tv.v1x1.common.dto.proto.core.PlatformOuterClass.Platform result = tv.v1x1.common.dto.proto.core.PlatformOuterClass.Platform.valueOf(type_);
        return result == null ? tv.v1x1.common.dto.proto.core.PlatformOuterClass.Platform.UNKNOWN : result;
      }
      /**
       * <code>required .tv.v1x1.common.dto.proto.core.Platform type = 2;</code>
       */
      public Builder setType(tv.v1x1.common.dto.proto.core.PlatformOuterClass.Platform value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>required .tv.v1x1.common.dto.proto.core.Platform type = 2;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        type_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:tv.v1x1.common.dto.proto.core.Bot)
    }

    // @@protoc_insertion_point(class_scope:tv.v1x1.common.dto.proto.core.Bot)
    private static final tv.v1x1.common.dto.proto.core.BotOuterClass.Bot DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new tv.v1x1.common.dto.proto.core.BotOuterClass.Bot();
    }

    public static tv.v1x1.common.dto.proto.core.BotOuterClass.Bot getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Bot>
        PARSER = new com.google.protobuf.AbstractParser<Bot>() {
      public Bot parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Bot(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Bot> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Bot> getParserForType() {
      return PARSER;
    }

    public tv.v1x1.common.dto.proto.core.BotOuterClass.Bot getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TwitchBotOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tv.v1x1.common.dto.proto.core.TwitchBot)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code tv.v1x1.common.dto.proto.core.TwitchBot}
   */
  public  static final class TwitchBot extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tv.v1x1.common.dto.proto.core.TwitchBot)
      TwitchBotOrBuilder {
    // Use TwitchBot.newBuilder() to construct.
    private TwitchBot(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TwitchBot() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TwitchBot(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return tv.v1x1.common.dto.proto.core.BotOuterClass.internal_static_tv_v1x1_common_dto_proto_core_TwitchBot_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return tv.v1x1.common.dto.proto.core.BotOuterClass.internal_static_tv_v1x1_common_dto_proto_core_TwitchBot_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              tv.v1x1.common.dto.proto.core.BotOuterClass.TwitchBot.class, tv.v1x1.common.dto.proto.core.BotOuterClass.TwitchBot.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof tv.v1x1.common.dto.proto.core.BotOuterClass.TwitchBot)) {
        return super.equals(obj);
      }
      tv.v1x1.common.dto.proto.core.BotOuterClass.TwitchBot other = (tv.v1x1.common.dto.proto.core.BotOuterClass.TwitchBot) obj;

      boolean result = true;
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static tv.v1x1.common.dto.proto.core.BotOuterClass.TwitchBot parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tv.v1x1.common.dto.proto.core.BotOuterClass.TwitchBot parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tv.v1x1.common.dto.proto.core.BotOuterClass.TwitchBot parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tv.v1x1.common.dto.proto.core.BotOuterClass.TwitchBot parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tv.v1x1.common.dto.proto.core.BotOuterClass.TwitchBot parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static tv.v1x1.common.dto.proto.core.BotOuterClass.TwitchBot parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static tv.v1x1.common.dto.proto.core.BotOuterClass.TwitchBot parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static tv.v1x1.common.dto.proto.core.BotOuterClass.TwitchBot parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static tv.v1x1.common.dto.proto.core.BotOuterClass.TwitchBot parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static tv.v1x1.common.dto.proto.core.BotOuterClass.TwitchBot parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(tv.v1x1.common.dto.proto.core.BotOuterClass.TwitchBot prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tv.v1x1.common.dto.proto.core.TwitchBot}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tv.v1x1.common.dto.proto.core.TwitchBot)
        tv.v1x1.common.dto.proto.core.BotOuterClass.TwitchBotOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return tv.v1x1.common.dto.proto.core.BotOuterClass.internal_static_tv_v1x1_common_dto_proto_core_TwitchBot_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return tv.v1x1.common.dto.proto.core.BotOuterClass.internal_static_tv_v1x1_common_dto_proto_core_TwitchBot_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                tv.v1x1.common.dto.proto.core.BotOuterClass.TwitchBot.class, tv.v1x1.common.dto.proto.core.BotOuterClass.TwitchBot.Builder.class);
      }

      // Construct using tv.v1x1.common.dto.proto.core.BotOuterClass.TwitchBot.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return tv.v1x1.common.dto.proto.core.BotOuterClass.internal_static_tv_v1x1_common_dto_proto_core_TwitchBot_descriptor;
      }

      public tv.v1x1.common.dto.proto.core.BotOuterClass.TwitchBot getDefaultInstanceForType() {
        return tv.v1x1.common.dto.proto.core.BotOuterClass.TwitchBot.getDefaultInstance();
      }

      public tv.v1x1.common.dto.proto.core.BotOuterClass.TwitchBot build() {
        tv.v1x1.common.dto.proto.core.BotOuterClass.TwitchBot result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public tv.v1x1.common.dto.proto.core.BotOuterClass.TwitchBot buildPartial() {
        tv.v1x1.common.dto.proto.core.BotOuterClass.TwitchBot result = new tv.v1x1.common.dto.proto.core.BotOuterClass.TwitchBot(this);
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof tv.v1x1.common.dto.proto.core.BotOuterClass.TwitchBot) {
          return mergeFrom((tv.v1x1.common.dto.proto.core.BotOuterClass.TwitchBot)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(tv.v1x1.common.dto.proto.core.BotOuterClass.TwitchBot other) {
        if (other == tv.v1x1.common.dto.proto.core.BotOuterClass.TwitchBot.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        tv.v1x1.common.dto.proto.core.BotOuterClass.TwitchBot parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (tv.v1x1.common.dto.proto.core.BotOuterClass.TwitchBot) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:tv.v1x1.common.dto.proto.core.TwitchBot)
    }

    // @@protoc_insertion_point(class_scope:tv.v1x1.common.dto.proto.core.TwitchBot)
    private static final tv.v1x1.common.dto.proto.core.BotOuterClass.TwitchBot DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new tv.v1x1.common.dto.proto.core.BotOuterClass.TwitchBot();
    }

    public static tv.v1x1.common.dto.proto.core.BotOuterClass.TwitchBot getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<TwitchBot>
        PARSER = new com.google.protobuf.AbstractParser<TwitchBot>() {
      public TwitchBot parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new TwitchBot(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TwitchBot> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TwitchBot> getParserForType() {
      return PARSER;
    }

    public tv.v1x1.common.dto.proto.core.BotOuterClass.TwitchBot getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

    public static final int DATA_FIELD_NUMBER = 101;
    /**
     * <code>extend .tv.v1x1.common.dto.proto.core.Bot { ... }</code>
     */
    public static final
      com.google.protobuf.GeneratedMessage.GeneratedExtension<
        tv.v1x1.common.dto.proto.core.BotOuterClass.Bot,
        tv.v1x1.common.dto.proto.core.BotOuterClass.TwitchBot> data = com.google.protobuf.GeneratedMessage
            .newMessageScopedGeneratedExtension(
          tv.v1x1.common.dto.proto.core.BotOuterClass.TwitchBot.getDefaultInstance(),
          0,
          tv.v1x1.common.dto.proto.core.BotOuterClass.TwitchBot.class,
          tv.v1x1.common.dto.proto.core.BotOuterClass.TwitchBot.getDefaultInstance());
  }

  public interface DiscordBotOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tv.v1x1.common.dto.proto.core.DiscordBot)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code tv.v1x1.common.dto.proto.core.DiscordBot}
   */
  public  static final class DiscordBot extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tv.v1x1.common.dto.proto.core.DiscordBot)
      DiscordBotOrBuilder {
    // Use DiscordBot.newBuilder() to construct.
    private DiscordBot(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DiscordBot() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DiscordBot(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return tv.v1x1.common.dto.proto.core.BotOuterClass.internal_static_tv_v1x1_common_dto_proto_core_DiscordBot_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return tv.v1x1.common.dto.proto.core.BotOuterClass.internal_static_tv_v1x1_common_dto_proto_core_DiscordBot_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              tv.v1x1.common.dto.proto.core.BotOuterClass.DiscordBot.class, tv.v1x1.common.dto.proto.core.BotOuterClass.DiscordBot.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof tv.v1x1.common.dto.proto.core.BotOuterClass.DiscordBot)) {
        return super.equals(obj);
      }
      tv.v1x1.common.dto.proto.core.BotOuterClass.DiscordBot other = (tv.v1x1.common.dto.proto.core.BotOuterClass.DiscordBot) obj;

      boolean result = true;
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static tv.v1x1.common.dto.proto.core.BotOuterClass.DiscordBot parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tv.v1x1.common.dto.proto.core.BotOuterClass.DiscordBot parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tv.v1x1.common.dto.proto.core.BotOuterClass.DiscordBot parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tv.v1x1.common.dto.proto.core.BotOuterClass.DiscordBot parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tv.v1x1.common.dto.proto.core.BotOuterClass.DiscordBot parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static tv.v1x1.common.dto.proto.core.BotOuterClass.DiscordBot parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static tv.v1x1.common.dto.proto.core.BotOuterClass.DiscordBot parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static tv.v1x1.common.dto.proto.core.BotOuterClass.DiscordBot parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static tv.v1x1.common.dto.proto.core.BotOuterClass.DiscordBot parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static tv.v1x1.common.dto.proto.core.BotOuterClass.DiscordBot parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(tv.v1x1.common.dto.proto.core.BotOuterClass.DiscordBot prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tv.v1x1.common.dto.proto.core.DiscordBot}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tv.v1x1.common.dto.proto.core.DiscordBot)
        tv.v1x1.common.dto.proto.core.BotOuterClass.DiscordBotOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return tv.v1x1.common.dto.proto.core.BotOuterClass.internal_static_tv_v1x1_common_dto_proto_core_DiscordBot_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return tv.v1x1.common.dto.proto.core.BotOuterClass.internal_static_tv_v1x1_common_dto_proto_core_DiscordBot_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                tv.v1x1.common.dto.proto.core.BotOuterClass.DiscordBot.class, tv.v1x1.common.dto.proto.core.BotOuterClass.DiscordBot.Builder.class);
      }

      // Construct using tv.v1x1.common.dto.proto.core.BotOuterClass.DiscordBot.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return tv.v1x1.common.dto.proto.core.BotOuterClass.internal_static_tv_v1x1_common_dto_proto_core_DiscordBot_descriptor;
      }

      public tv.v1x1.common.dto.proto.core.BotOuterClass.DiscordBot getDefaultInstanceForType() {
        return tv.v1x1.common.dto.proto.core.BotOuterClass.DiscordBot.getDefaultInstance();
      }

      public tv.v1x1.common.dto.proto.core.BotOuterClass.DiscordBot build() {
        tv.v1x1.common.dto.proto.core.BotOuterClass.DiscordBot result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public tv.v1x1.common.dto.proto.core.BotOuterClass.DiscordBot buildPartial() {
        tv.v1x1.common.dto.proto.core.BotOuterClass.DiscordBot result = new tv.v1x1.common.dto.proto.core.BotOuterClass.DiscordBot(this);
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof tv.v1x1.common.dto.proto.core.BotOuterClass.DiscordBot) {
          return mergeFrom((tv.v1x1.common.dto.proto.core.BotOuterClass.DiscordBot)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(tv.v1x1.common.dto.proto.core.BotOuterClass.DiscordBot other) {
        if (other == tv.v1x1.common.dto.proto.core.BotOuterClass.DiscordBot.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        tv.v1x1.common.dto.proto.core.BotOuterClass.DiscordBot parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (tv.v1x1.common.dto.proto.core.BotOuterClass.DiscordBot) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:tv.v1x1.common.dto.proto.core.DiscordBot)
    }

    // @@protoc_insertion_point(class_scope:tv.v1x1.common.dto.proto.core.DiscordBot)
    private static final tv.v1x1.common.dto.proto.core.BotOuterClass.DiscordBot DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new tv.v1x1.common.dto.proto.core.BotOuterClass.DiscordBot();
    }

    public static tv.v1x1.common.dto.proto.core.BotOuterClass.DiscordBot getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<DiscordBot>
        PARSER = new com.google.protobuf.AbstractParser<DiscordBot>() {
      public DiscordBot parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new DiscordBot(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DiscordBot> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DiscordBot> getParserForType() {
      return PARSER;
    }

    public tv.v1x1.common.dto.proto.core.BotOuterClass.DiscordBot getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

    public static final int DATA_FIELD_NUMBER = 102;
    /**
     * <code>extend .tv.v1x1.common.dto.proto.core.Bot { ... }</code>
     */
    public static final
      com.google.protobuf.GeneratedMessage.GeneratedExtension<
        tv.v1x1.common.dto.proto.core.BotOuterClass.Bot,
        tv.v1x1.common.dto.proto.core.BotOuterClass.DiscordBot> data = com.google.protobuf.GeneratedMessage
            .newMessageScopedGeneratedExtension(
          tv.v1x1.common.dto.proto.core.BotOuterClass.DiscordBot.getDefaultInstance(),
          0,
          tv.v1x1.common.dto.proto.core.BotOuterClass.DiscordBot.class,
          tv.v1x1.common.dto.proto.core.BotOuterClass.DiscordBot.getDefaultInstance());
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tv_v1x1_common_dto_proto_core_Bot_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tv_v1x1_common_dto_proto_core_Bot_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tv_v1x1_common_dto_proto_core_TwitchBot_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tv_v1x1_common_dto_proto_core_TwitchBot_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tv_v1x1_common_dto_proto_core_DiscordBot_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tv_v1x1_common_dto_proto_core_DiscordBot_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tBot.proto\022\035tv.v1x1.common.dto.proto.co" +
      "re\032\016Platform.proto\"T\n\003Bot\022\014\n\004name\030\001 \002(\t\022" +
      "5\n\004type\030\002 \002(\0162\'.tv.v1x1.common.dto.proto" +
      ".core.Platform*\010\010d\020\200\200\200\200\002\"g\n\tTwitchBot2Z\n" +
      "\004data\022\".tv.v1x1.common.dto.proto.core.Bo" +
      "t\030e \001(\0132(.tv.v1x1.common.dto.proto.core." +
      "TwitchBot\"i\n\nDiscordBot2[\n\004data\022\".tv.v1x" +
      "1.common.dto.proto.core.Bot\030f \001(\0132).tv.v" +
      "1x1.common.dto.proto.core.DiscordBot"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          tv.v1x1.common.dto.proto.core.PlatformOuterClass.getDescriptor(),
        }, assigner);
    internal_static_tv_v1x1_common_dto_proto_core_Bot_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tv_v1x1_common_dto_proto_core_Bot_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tv_v1x1_common_dto_proto_core_Bot_descriptor,
        new java.lang.String[] { "Name", "Type", });
    internal_static_tv_v1x1_common_dto_proto_core_TwitchBot_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_tv_v1x1_common_dto_proto_core_TwitchBot_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tv_v1x1_common_dto_proto_core_TwitchBot_descriptor,
        new java.lang.String[] { });
    internal_static_tv_v1x1_common_dto_proto_core_DiscordBot_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_tv_v1x1_common_dto_proto_core_DiscordBot_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tv_v1x1_common_dto_proto_core_DiscordBot_descriptor,
        new java.lang.String[] { });
    tv.v1x1.common.dto.proto.core.PlatformOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
