// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ChatMessage.proto

package tv.v1x1.common.dto.proto.core;

public final class ChatMessageOuterClass {
  private ChatMessageOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ChatMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tv.v1x1.common.dto.proto.core.ChatMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .tv.v1x1.common.dto.proto.core.Channel channel = 1;</code>
     */
    boolean hasChannel();
    /**
     * <code>required .tv.v1x1.common.dto.proto.core.Channel channel = 1;</code>
     */
    tv.v1x1.common.dto.proto.core.ChannelOuterClass.Channel getChannel();
    /**
     * <code>required .tv.v1x1.common.dto.proto.core.Channel channel = 1;</code>
     */
    tv.v1x1.common.dto.proto.core.ChannelOuterClass.ChannelOrBuilder getChannelOrBuilder();

    /**
     * <code>required .tv.v1x1.common.dto.proto.core.User sender = 2;</code>
     */
    boolean hasSender();
    /**
     * <code>required .tv.v1x1.common.dto.proto.core.User sender = 2;</code>
     */
    tv.v1x1.common.dto.proto.core.UserOuterClass.User getSender();
    /**
     * <code>required .tv.v1x1.common.dto.proto.core.User sender = 2;</code>
     */
    tv.v1x1.common.dto.proto.core.UserOuterClass.UserOrBuilder getSenderOrBuilder();

    /**
     * <code>required string text = 3;</code>
     */
    boolean hasText();
    /**
     * <code>required string text = 3;</code>
     */
    java.lang.String getText();
    /**
     * <code>required string text = 3;</code>
     */
    com.google.protobuf.ByteString
        getTextBytes();

    /**
     * <code>repeated .tv.v1x1.common.dto.proto.core.Permission permissions = 4;</code>
     */
    java.util.List<tv.v1x1.common.dto.proto.core.PermissionOuterClass.Permission> 
        getPermissionsList();
    /**
     * <code>repeated .tv.v1x1.common.dto.proto.core.Permission permissions = 4;</code>
     */
    tv.v1x1.common.dto.proto.core.PermissionOuterClass.Permission getPermissions(int index);
    /**
     * <code>repeated .tv.v1x1.common.dto.proto.core.Permission permissions = 4;</code>
     */
    int getPermissionsCount();
    /**
     * <code>repeated .tv.v1x1.common.dto.proto.core.Permission permissions = 4;</code>
     */
    java.util.List<? extends tv.v1x1.common.dto.proto.core.PermissionOuterClass.PermissionOrBuilder> 
        getPermissionsOrBuilderList();
    /**
     * <code>repeated .tv.v1x1.common.dto.proto.core.Permission permissions = 4;</code>
     */
    tv.v1x1.common.dto.proto.core.PermissionOuterClass.PermissionOrBuilder getPermissionsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code tv.v1x1.common.dto.proto.core.ChatMessage}
   */
  public  static final class ChatMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tv.v1x1.common.dto.proto.core.ChatMessage)
      ChatMessageOrBuilder {
    // Use ChatMessage.newBuilder() to construct.
    private ChatMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ChatMessage() {
      text_ = "";
      permissions_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ChatMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              tv.v1x1.common.dto.proto.core.ChannelOuterClass.Channel.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = channel_.toBuilder();
              }
              channel_ = input.readMessage(tv.v1x1.common.dto.proto.core.ChannelOuterClass.Channel.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(channel_);
                channel_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              tv.v1x1.common.dto.proto.core.UserOuterClass.User.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = sender_.toBuilder();
              }
              sender_ = input.readMessage(tv.v1x1.common.dto.proto.core.UserOuterClass.User.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(sender_);
                sender_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              text_ = bs;
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                permissions_ = new java.util.ArrayList<tv.v1x1.common.dto.proto.core.PermissionOuterClass.Permission>();
                mutable_bitField0_ |= 0x00000008;
              }
              permissions_.add(
                  input.readMessage(tv.v1x1.common.dto.proto.core.PermissionOuterClass.Permission.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          permissions_ = java.util.Collections.unmodifiableList(permissions_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return tv.v1x1.common.dto.proto.core.ChatMessageOuterClass.internal_static_tv_v1x1_common_dto_proto_core_ChatMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return tv.v1x1.common.dto.proto.core.ChatMessageOuterClass.internal_static_tv_v1x1_common_dto_proto_core_ChatMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              tv.v1x1.common.dto.proto.core.ChatMessageOuterClass.ChatMessage.class, tv.v1x1.common.dto.proto.core.ChatMessageOuterClass.ChatMessage.Builder.class);
    }

    private int bitField0_;
    public static final int CHANNEL_FIELD_NUMBER = 1;
    private tv.v1x1.common.dto.proto.core.ChannelOuterClass.Channel channel_;
    /**
     * <code>required .tv.v1x1.common.dto.proto.core.Channel channel = 1;</code>
     */
    public boolean hasChannel() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .tv.v1x1.common.dto.proto.core.Channel channel = 1;</code>
     */
    public tv.v1x1.common.dto.proto.core.ChannelOuterClass.Channel getChannel() {
      return channel_ == null ? tv.v1x1.common.dto.proto.core.ChannelOuterClass.Channel.getDefaultInstance() : channel_;
    }
    /**
     * <code>required .tv.v1x1.common.dto.proto.core.Channel channel = 1;</code>
     */
    public tv.v1x1.common.dto.proto.core.ChannelOuterClass.ChannelOrBuilder getChannelOrBuilder() {
      return channel_ == null ? tv.v1x1.common.dto.proto.core.ChannelOuterClass.Channel.getDefaultInstance() : channel_;
    }

    public static final int SENDER_FIELD_NUMBER = 2;
    private tv.v1x1.common.dto.proto.core.UserOuterClass.User sender_;
    /**
     * <code>required .tv.v1x1.common.dto.proto.core.User sender = 2;</code>
     */
    public boolean hasSender() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .tv.v1x1.common.dto.proto.core.User sender = 2;</code>
     */
    public tv.v1x1.common.dto.proto.core.UserOuterClass.User getSender() {
      return sender_ == null ? tv.v1x1.common.dto.proto.core.UserOuterClass.User.getDefaultInstance() : sender_;
    }
    /**
     * <code>required .tv.v1x1.common.dto.proto.core.User sender = 2;</code>
     */
    public tv.v1x1.common.dto.proto.core.UserOuterClass.UserOrBuilder getSenderOrBuilder() {
      return sender_ == null ? tv.v1x1.common.dto.proto.core.UserOuterClass.User.getDefaultInstance() : sender_;
    }

    public static final int TEXT_FIELD_NUMBER = 3;
    private volatile java.lang.Object text_;
    /**
     * <code>required string text = 3;</code>
     */
    public boolean hasText() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string text = 3;</code>
     */
    public java.lang.String getText() {
      java.lang.Object ref = text_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          text_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string text = 3;</code>
     */
    public com.google.protobuf.ByteString
        getTextBytes() {
      java.lang.Object ref = text_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        text_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PERMISSIONS_FIELD_NUMBER = 4;
    private java.util.List<tv.v1x1.common.dto.proto.core.PermissionOuterClass.Permission> permissions_;
    /**
     * <code>repeated .tv.v1x1.common.dto.proto.core.Permission permissions = 4;</code>
     */
    public java.util.List<tv.v1x1.common.dto.proto.core.PermissionOuterClass.Permission> getPermissionsList() {
      return permissions_;
    }
    /**
     * <code>repeated .tv.v1x1.common.dto.proto.core.Permission permissions = 4;</code>
     */
    public java.util.List<? extends tv.v1x1.common.dto.proto.core.PermissionOuterClass.PermissionOrBuilder> 
        getPermissionsOrBuilderList() {
      return permissions_;
    }
    /**
     * <code>repeated .tv.v1x1.common.dto.proto.core.Permission permissions = 4;</code>
     */
    public int getPermissionsCount() {
      return permissions_.size();
    }
    /**
     * <code>repeated .tv.v1x1.common.dto.proto.core.Permission permissions = 4;</code>
     */
    public tv.v1x1.common.dto.proto.core.PermissionOuterClass.Permission getPermissions(int index) {
      return permissions_.get(index);
    }
    /**
     * <code>repeated .tv.v1x1.common.dto.proto.core.Permission permissions = 4;</code>
     */
    public tv.v1x1.common.dto.proto.core.PermissionOuterClass.PermissionOrBuilder getPermissionsOrBuilder(
        int index) {
      return permissions_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasChannel()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSender()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasText()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getChannel().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getSender().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getPermissionsCount(); i++) {
        if (!getPermissions(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, getChannel());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, getSender());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, text_);
      }
      for (int i = 0; i < permissions_.size(); i++) {
        output.writeMessage(4, permissions_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getChannel());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getSender());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, text_);
      }
      for (int i = 0; i < permissions_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, permissions_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof tv.v1x1.common.dto.proto.core.ChatMessageOuterClass.ChatMessage)) {
        return super.equals(obj);
      }
      tv.v1x1.common.dto.proto.core.ChatMessageOuterClass.ChatMessage other = (tv.v1x1.common.dto.proto.core.ChatMessageOuterClass.ChatMessage) obj;

      boolean result = true;
      result = result && (hasChannel() == other.hasChannel());
      if (hasChannel()) {
        result = result && getChannel()
            .equals(other.getChannel());
      }
      result = result && (hasSender() == other.hasSender());
      if (hasSender()) {
        result = result && getSender()
            .equals(other.getSender());
      }
      result = result && (hasText() == other.hasText());
      if (hasText()) {
        result = result && getText()
            .equals(other.getText());
      }
      result = result && getPermissionsList()
          .equals(other.getPermissionsList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasChannel()) {
        hash = (37 * hash) + CHANNEL_FIELD_NUMBER;
        hash = (53 * hash) + getChannel().hashCode();
      }
      if (hasSender()) {
        hash = (37 * hash) + SENDER_FIELD_NUMBER;
        hash = (53 * hash) + getSender().hashCode();
      }
      if (hasText()) {
        hash = (37 * hash) + TEXT_FIELD_NUMBER;
        hash = (53 * hash) + getText().hashCode();
      }
      if (getPermissionsCount() > 0) {
        hash = (37 * hash) + PERMISSIONS_FIELD_NUMBER;
        hash = (53 * hash) + getPermissionsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static tv.v1x1.common.dto.proto.core.ChatMessageOuterClass.ChatMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tv.v1x1.common.dto.proto.core.ChatMessageOuterClass.ChatMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tv.v1x1.common.dto.proto.core.ChatMessageOuterClass.ChatMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tv.v1x1.common.dto.proto.core.ChatMessageOuterClass.ChatMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tv.v1x1.common.dto.proto.core.ChatMessageOuterClass.ChatMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static tv.v1x1.common.dto.proto.core.ChatMessageOuterClass.ChatMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static tv.v1x1.common.dto.proto.core.ChatMessageOuterClass.ChatMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static tv.v1x1.common.dto.proto.core.ChatMessageOuterClass.ChatMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static tv.v1x1.common.dto.proto.core.ChatMessageOuterClass.ChatMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static tv.v1x1.common.dto.proto.core.ChatMessageOuterClass.ChatMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(tv.v1x1.common.dto.proto.core.ChatMessageOuterClass.ChatMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tv.v1x1.common.dto.proto.core.ChatMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tv.v1x1.common.dto.proto.core.ChatMessage)
        tv.v1x1.common.dto.proto.core.ChatMessageOuterClass.ChatMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return tv.v1x1.common.dto.proto.core.ChatMessageOuterClass.internal_static_tv_v1x1_common_dto_proto_core_ChatMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return tv.v1x1.common.dto.proto.core.ChatMessageOuterClass.internal_static_tv_v1x1_common_dto_proto_core_ChatMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                tv.v1x1.common.dto.proto.core.ChatMessageOuterClass.ChatMessage.class, tv.v1x1.common.dto.proto.core.ChatMessageOuterClass.ChatMessage.Builder.class);
      }

      // Construct using tv.v1x1.common.dto.proto.core.ChatMessageOuterClass.ChatMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getChannelFieldBuilder();
          getSenderFieldBuilder();
          getPermissionsFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (channelBuilder_ == null) {
          channel_ = null;
        } else {
          channelBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        if (senderBuilder_ == null) {
          sender_ = null;
        } else {
          senderBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        text_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        if (permissionsBuilder_ == null) {
          permissions_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          permissionsBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return tv.v1x1.common.dto.proto.core.ChatMessageOuterClass.internal_static_tv_v1x1_common_dto_proto_core_ChatMessage_descriptor;
      }

      public tv.v1x1.common.dto.proto.core.ChatMessageOuterClass.ChatMessage getDefaultInstanceForType() {
        return tv.v1x1.common.dto.proto.core.ChatMessageOuterClass.ChatMessage.getDefaultInstance();
      }

      public tv.v1x1.common.dto.proto.core.ChatMessageOuterClass.ChatMessage build() {
        tv.v1x1.common.dto.proto.core.ChatMessageOuterClass.ChatMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public tv.v1x1.common.dto.proto.core.ChatMessageOuterClass.ChatMessage buildPartial() {
        tv.v1x1.common.dto.proto.core.ChatMessageOuterClass.ChatMessage result = new tv.v1x1.common.dto.proto.core.ChatMessageOuterClass.ChatMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (channelBuilder_ == null) {
          result.channel_ = channel_;
        } else {
          result.channel_ = channelBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (senderBuilder_ == null) {
          result.sender_ = sender_;
        } else {
          result.sender_ = senderBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.text_ = text_;
        if (permissionsBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008)) {
            permissions_ = java.util.Collections.unmodifiableList(permissions_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.permissions_ = permissions_;
        } else {
          result.permissions_ = permissionsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof tv.v1x1.common.dto.proto.core.ChatMessageOuterClass.ChatMessage) {
          return mergeFrom((tv.v1x1.common.dto.proto.core.ChatMessageOuterClass.ChatMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(tv.v1x1.common.dto.proto.core.ChatMessageOuterClass.ChatMessage other) {
        if (other == tv.v1x1.common.dto.proto.core.ChatMessageOuterClass.ChatMessage.getDefaultInstance()) return this;
        if (other.hasChannel()) {
          mergeChannel(other.getChannel());
        }
        if (other.hasSender()) {
          mergeSender(other.getSender());
        }
        if (other.hasText()) {
          bitField0_ |= 0x00000004;
          text_ = other.text_;
          onChanged();
        }
        if (permissionsBuilder_ == null) {
          if (!other.permissions_.isEmpty()) {
            if (permissions_.isEmpty()) {
              permissions_ = other.permissions_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensurePermissionsIsMutable();
              permissions_.addAll(other.permissions_);
            }
            onChanged();
          }
        } else {
          if (!other.permissions_.isEmpty()) {
            if (permissionsBuilder_.isEmpty()) {
              permissionsBuilder_.dispose();
              permissionsBuilder_ = null;
              permissions_ = other.permissions_;
              bitField0_ = (bitField0_ & ~0x00000008);
              permissionsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getPermissionsFieldBuilder() : null;
            } else {
              permissionsBuilder_.addAllMessages(other.permissions_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasChannel()) {
          return false;
        }
        if (!hasSender()) {
          return false;
        }
        if (!hasText()) {
          return false;
        }
        if (!getChannel().isInitialized()) {
          return false;
        }
        if (!getSender().isInitialized()) {
          return false;
        }
        for (int i = 0; i < getPermissionsCount(); i++) {
          if (!getPermissions(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        tv.v1x1.common.dto.proto.core.ChatMessageOuterClass.ChatMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (tv.v1x1.common.dto.proto.core.ChatMessageOuterClass.ChatMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private tv.v1x1.common.dto.proto.core.ChannelOuterClass.Channel channel_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          tv.v1x1.common.dto.proto.core.ChannelOuterClass.Channel, tv.v1x1.common.dto.proto.core.ChannelOuterClass.Channel.Builder, tv.v1x1.common.dto.proto.core.ChannelOuterClass.ChannelOrBuilder> channelBuilder_;
      /**
       * <code>required .tv.v1x1.common.dto.proto.core.Channel channel = 1;</code>
       */
      public boolean hasChannel() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .tv.v1x1.common.dto.proto.core.Channel channel = 1;</code>
       */
      public tv.v1x1.common.dto.proto.core.ChannelOuterClass.Channel getChannel() {
        if (channelBuilder_ == null) {
          return channel_ == null ? tv.v1x1.common.dto.proto.core.ChannelOuterClass.Channel.getDefaultInstance() : channel_;
        } else {
          return channelBuilder_.getMessage();
        }
      }
      /**
       * <code>required .tv.v1x1.common.dto.proto.core.Channel channel = 1;</code>
       */
      public Builder setChannel(tv.v1x1.common.dto.proto.core.ChannelOuterClass.Channel value) {
        if (channelBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          channel_ = value;
          onChanged();
        } else {
          channelBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .tv.v1x1.common.dto.proto.core.Channel channel = 1;</code>
       */
      public Builder setChannel(
          tv.v1x1.common.dto.proto.core.ChannelOuterClass.Channel.Builder builderForValue) {
        if (channelBuilder_ == null) {
          channel_ = builderForValue.build();
          onChanged();
        } else {
          channelBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .tv.v1x1.common.dto.proto.core.Channel channel = 1;</code>
       */
      public Builder mergeChannel(tv.v1x1.common.dto.proto.core.ChannelOuterClass.Channel value) {
        if (channelBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              channel_ != null &&
              channel_ != tv.v1x1.common.dto.proto.core.ChannelOuterClass.Channel.getDefaultInstance()) {
            channel_ =
              tv.v1x1.common.dto.proto.core.ChannelOuterClass.Channel.newBuilder(channel_).mergeFrom(value).buildPartial();
          } else {
            channel_ = value;
          }
          onChanged();
        } else {
          channelBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .tv.v1x1.common.dto.proto.core.Channel channel = 1;</code>
       */
      public Builder clearChannel() {
        if (channelBuilder_ == null) {
          channel_ = null;
          onChanged();
        } else {
          channelBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>required .tv.v1x1.common.dto.proto.core.Channel channel = 1;</code>
       */
      public tv.v1x1.common.dto.proto.core.ChannelOuterClass.Channel.Builder getChannelBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getChannelFieldBuilder().getBuilder();
      }
      /**
       * <code>required .tv.v1x1.common.dto.proto.core.Channel channel = 1;</code>
       */
      public tv.v1x1.common.dto.proto.core.ChannelOuterClass.ChannelOrBuilder getChannelOrBuilder() {
        if (channelBuilder_ != null) {
          return channelBuilder_.getMessageOrBuilder();
        } else {
          return channel_ == null ?
              tv.v1x1.common.dto.proto.core.ChannelOuterClass.Channel.getDefaultInstance() : channel_;
        }
      }
      /**
       * <code>required .tv.v1x1.common.dto.proto.core.Channel channel = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          tv.v1x1.common.dto.proto.core.ChannelOuterClass.Channel, tv.v1x1.common.dto.proto.core.ChannelOuterClass.Channel.Builder, tv.v1x1.common.dto.proto.core.ChannelOuterClass.ChannelOrBuilder> 
          getChannelFieldBuilder() {
        if (channelBuilder_ == null) {
          channelBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              tv.v1x1.common.dto.proto.core.ChannelOuterClass.Channel, tv.v1x1.common.dto.proto.core.ChannelOuterClass.Channel.Builder, tv.v1x1.common.dto.proto.core.ChannelOuterClass.ChannelOrBuilder>(
                  getChannel(),
                  getParentForChildren(),
                  isClean());
          channel_ = null;
        }
        return channelBuilder_;
      }

      private tv.v1x1.common.dto.proto.core.UserOuterClass.User sender_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          tv.v1x1.common.dto.proto.core.UserOuterClass.User, tv.v1x1.common.dto.proto.core.UserOuterClass.User.Builder, tv.v1x1.common.dto.proto.core.UserOuterClass.UserOrBuilder> senderBuilder_;
      /**
       * <code>required .tv.v1x1.common.dto.proto.core.User sender = 2;</code>
       */
      public boolean hasSender() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .tv.v1x1.common.dto.proto.core.User sender = 2;</code>
       */
      public tv.v1x1.common.dto.proto.core.UserOuterClass.User getSender() {
        if (senderBuilder_ == null) {
          return sender_ == null ? tv.v1x1.common.dto.proto.core.UserOuterClass.User.getDefaultInstance() : sender_;
        } else {
          return senderBuilder_.getMessage();
        }
      }
      /**
       * <code>required .tv.v1x1.common.dto.proto.core.User sender = 2;</code>
       */
      public Builder setSender(tv.v1x1.common.dto.proto.core.UserOuterClass.User value) {
        if (senderBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          sender_ = value;
          onChanged();
        } else {
          senderBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .tv.v1x1.common.dto.proto.core.User sender = 2;</code>
       */
      public Builder setSender(
          tv.v1x1.common.dto.proto.core.UserOuterClass.User.Builder builderForValue) {
        if (senderBuilder_ == null) {
          sender_ = builderForValue.build();
          onChanged();
        } else {
          senderBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .tv.v1x1.common.dto.proto.core.User sender = 2;</code>
       */
      public Builder mergeSender(tv.v1x1.common.dto.proto.core.UserOuterClass.User value) {
        if (senderBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              sender_ != null &&
              sender_ != tv.v1x1.common.dto.proto.core.UserOuterClass.User.getDefaultInstance()) {
            sender_ =
              tv.v1x1.common.dto.proto.core.UserOuterClass.User.newBuilder(sender_).mergeFrom(value).buildPartial();
          } else {
            sender_ = value;
          }
          onChanged();
        } else {
          senderBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .tv.v1x1.common.dto.proto.core.User sender = 2;</code>
       */
      public Builder clearSender() {
        if (senderBuilder_ == null) {
          sender_ = null;
          onChanged();
        } else {
          senderBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>required .tv.v1x1.common.dto.proto.core.User sender = 2;</code>
       */
      public tv.v1x1.common.dto.proto.core.UserOuterClass.User.Builder getSenderBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getSenderFieldBuilder().getBuilder();
      }
      /**
       * <code>required .tv.v1x1.common.dto.proto.core.User sender = 2;</code>
       */
      public tv.v1x1.common.dto.proto.core.UserOuterClass.UserOrBuilder getSenderOrBuilder() {
        if (senderBuilder_ != null) {
          return senderBuilder_.getMessageOrBuilder();
        } else {
          return sender_ == null ?
              tv.v1x1.common.dto.proto.core.UserOuterClass.User.getDefaultInstance() : sender_;
        }
      }
      /**
       * <code>required .tv.v1x1.common.dto.proto.core.User sender = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          tv.v1x1.common.dto.proto.core.UserOuterClass.User, tv.v1x1.common.dto.proto.core.UserOuterClass.User.Builder, tv.v1x1.common.dto.proto.core.UserOuterClass.UserOrBuilder> 
          getSenderFieldBuilder() {
        if (senderBuilder_ == null) {
          senderBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              tv.v1x1.common.dto.proto.core.UserOuterClass.User, tv.v1x1.common.dto.proto.core.UserOuterClass.User.Builder, tv.v1x1.common.dto.proto.core.UserOuterClass.UserOrBuilder>(
                  getSender(),
                  getParentForChildren(),
                  isClean());
          sender_ = null;
        }
        return senderBuilder_;
      }

      private java.lang.Object text_ = "";
      /**
       * <code>required string text = 3;</code>
       */
      public boolean hasText() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string text = 3;</code>
       */
      public java.lang.String getText() {
        java.lang.Object ref = text_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            text_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string text = 3;</code>
       */
      public com.google.protobuf.ByteString
          getTextBytes() {
        java.lang.Object ref = text_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          text_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string text = 3;</code>
       */
      public Builder setText(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        text_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string text = 3;</code>
       */
      public Builder clearText() {
        bitField0_ = (bitField0_ & ~0x00000004);
        text_ = getDefaultInstance().getText();
        onChanged();
        return this;
      }
      /**
       * <code>required string text = 3;</code>
       */
      public Builder setTextBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        text_ = value;
        onChanged();
        return this;
      }

      private java.util.List<tv.v1x1.common.dto.proto.core.PermissionOuterClass.Permission> permissions_ =
        java.util.Collections.emptyList();
      private void ensurePermissionsIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          permissions_ = new java.util.ArrayList<tv.v1x1.common.dto.proto.core.PermissionOuterClass.Permission>(permissions_);
          bitField0_ |= 0x00000008;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          tv.v1x1.common.dto.proto.core.PermissionOuterClass.Permission, tv.v1x1.common.dto.proto.core.PermissionOuterClass.Permission.Builder, tv.v1x1.common.dto.proto.core.PermissionOuterClass.PermissionOrBuilder> permissionsBuilder_;

      /**
       * <code>repeated .tv.v1x1.common.dto.proto.core.Permission permissions = 4;</code>
       */
      public java.util.List<tv.v1x1.common.dto.proto.core.PermissionOuterClass.Permission> getPermissionsList() {
        if (permissionsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(permissions_);
        } else {
          return permissionsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .tv.v1x1.common.dto.proto.core.Permission permissions = 4;</code>
       */
      public int getPermissionsCount() {
        if (permissionsBuilder_ == null) {
          return permissions_.size();
        } else {
          return permissionsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .tv.v1x1.common.dto.proto.core.Permission permissions = 4;</code>
       */
      public tv.v1x1.common.dto.proto.core.PermissionOuterClass.Permission getPermissions(int index) {
        if (permissionsBuilder_ == null) {
          return permissions_.get(index);
        } else {
          return permissionsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .tv.v1x1.common.dto.proto.core.Permission permissions = 4;</code>
       */
      public Builder setPermissions(
          int index, tv.v1x1.common.dto.proto.core.PermissionOuterClass.Permission value) {
        if (permissionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePermissionsIsMutable();
          permissions_.set(index, value);
          onChanged();
        } else {
          permissionsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .tv.v1x1.common.dto.proto.core.Permission permissions = 4;</code>
       */
      public Builder setPermissions(
          int index, tv.v1x1.common.dto.proto.core.PermissionOuterClass.Permission.Builder builderForValue) {
        if (permissionsBuilder_ == null) {
          ensurePermissionsIsMutable();
          permissions_.set(index, builderForValue.build());
          onChanged();
        } else {
          permissionsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .tv.v1x1.common.dto.proto.core.Permission permissions = 4;</code>
       */
      public Builder addPermissions(tv.v1x1.common.dto.proto.core.PermissionOuterClass.Permission value) {
        if (permissionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePermissionsIsMutable();
          permissions_.add(value);
          onChanged();
        } else {
          permissionsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .tv.v1x1.common.dto.proto.core.Permission permissions = 4;</code>
       */
      public Builder addPermissions(
          int index, tv.v1x1.common.dto.proto.core.PermissionOuterClass.Permission value) {
        if (permissionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePermissionsIsMutable();
          permissions_.add(index, value);
          onChanged();
        } else {
          permissionsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .tv.v1x1.common.dto.proto.core.Permission permissions = 4;</code>
       */
      public Builder addPermissions(
          tv.v1x1.common.dto.proto.core.PermissionOuterClass.Permission.Builder builderForValue) {
        if (permissionsBuilder_ == null) {
          ensurePermissionsIsMutable();
          permissions_.add(builderForValue.build());
          onChanged();
        } else {
          permissionsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .tv.v1x1.common.dto.proto.core.Permission permissions = 4;</code>
       */
      public Builder addPermissions(
          int index, tv.v1x1.common.dto.proto.core.PermissionOuterClass.Permission.Builder builderForValue) {
        if (permissionsBuilder_ == null) {
          ensurePermissionsIsMutable();
          permissions_.add(index, builderForValue.build());
          onChanged();
        } else {
          permissionsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .tv.v1x1.common.dto.proto.core.Permission permissions = 4;</code>
       */
      public Builder addAllPermissions(
          java.lang.Iterable<? extends tv.v1x1.common.dto.proto.core.PermissionOuterClass.Permission> values) {
        if (permissionsBuilder_ == null) {
          ensurePermissionsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, permissions_);
          onChanged();
        } else {
          permissionsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .tv.v1x1.common.dto.proto.core.Permission permissions = 4;</code>
       */
      public Builder clearPermissions() {
        if (permissionsBuilder_ == null) {
          permissions_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          permissionsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .tv.v1x1.common.dto.proto.core.Permission permissions = 4;</code>
       */
      public Builder removePermissions(int index) {
        if (permissionsBuilder_ == null) {
          ensurePermissionsIsMutable();
          permissions_.remove(index);
          onChanged();
        } else {
          permissionsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .tv.v1x1.common.dto.proto.core.Permission permissions = 4;</code>
       */
      public tv.v1x1.common.dto.proto.core.PermissionOuterClass.Permission.Builder getPermissionsBuilder(
          int index) {
        return getPermissionsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .tv.v1x1.common.dto.proto.core.Permission permissions = 4;</code>
       */
      public tv.v1x1.common.dto.proto.core.PermissionOuterClass.PermissionOrBuilder getPermissionsOrBuilder(
          int index) {
        if (permissionsBuilder_ == null) {
          return permissions_.get(index);  } else {
          return permissionsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .tv.v1x1.common.dto.proto.core.Permission permissions = 4;</code>
       */
      public java.util.List<? extends tv.v1x1.common.dto.proto.core.PermissionOuterClass.PermissionOrBuilder> 
           getPermissionsOrBuilderList() {
        if (permissionsBuilder_ != null) {
          return permissionsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(permissions_);
        }
      }
      /**
       * <code>repeated .tv.v1x1.common.dto.proto.core.Permission permissions = 4;</code>
       */
      public tv.v1x1.common.dto.proto.core.PermissionOuterClass.Permission.Builder addPermissionsBuilder() {
        return getPermissionsFieldBuilder().addBuilder(
            tv.v1x1.common.dto.proto.core.PermissionOuterClass.Permission.getDefaultInstance());
      }
      /**
       * <code>repeated .tv.v1x1.common.dto.proto.core.Permission permissions = 4;</code>
       */
      public tv.v1x1.common.dto.proto.core.PermissionOuterClass.Permission.Builder addPermissionsBuilder(
          int index) {
        return getPermissionsFieldBuilder().addBuilder(
            index, tv.v1x1.common.dto.proto.core.PermissionOuterClass.Permission.getDefaultInstance());
      }
      /**
       * <code>repeated .tv.v1x1.common.dto.proto.core.Permission permissions = 4;</code>
       */
      public java.util.List<tv.v1x1.common.dto.proto.core.PermissionOuterClass.Permission.Builder> 
           getPermissionsBuilderList() {
        return getPermissionsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          tv.v1x1.common.dto.proto.core.PermissionOuterClass.Permission, tv.v1x1.common.dto.proto.core.PermissionOuterClass.Permission.Builder, tv.v1x1.common.dto.proto.core.PermissionOuterClass.PermissionOrBuilder> 
          getPermissionsFieldBuilder() {
        if (permissionsBuilder_ == null) {
          permissionsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              tv.v1x1.common.dto.proto.core.PermissionOuterClass.Permission, tv.v1x1.common.dto.proto.core.PermissionOuterClass.Permission.Builder, tv.v1x1.common.dto.proto.core.PermissionOuterClass.PermissionOrBuilder>(
                  permissions_,
                  ((bitField0_ & 0x00000008) == 0x00000008),
                  getParentForChildren(),
                  isClean());
          permissions_ = null;
        }
        return permissionsBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:tv.v1x1.common.dto.proto.core.ChatMessage)
    }

    // @@protoc_insertion_point(class_scope:tv.v1x1.common.dto.proto.core.ChatMessage)
    private static final tv.v1x1.common.dto.proto.core.ChatMessageOuterClass.ChatMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new tv.v1x1.common.dto.proto.core.ChatMessageOuterClass.ChatMessage();
    }

    public static tv.v1x1.common.dto.proto.core.ChatMessageOuterClass.ChatMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<ChatMessage>
        PARSER = new com.google.protobuf.AbstractParser<ChatMessage>() {
      public ChatMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ChatMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ChatMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ChatMessage> getParserForType() {
      return PARSER;
    }

    public tv.v1x1.common.dto.proto.core.ChatMessageOuterClass.ChatMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tv_v1x1_common_dto_proto_core_ChatMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tv_v1x1_common_dto_proto_core_ChatMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021ChatMessage.proto\022\035tv.v1x1.common.dto." +
      "proto.core\032\rChannel.proto\032\nUser.proto\032\020P" +
      "ermission.proto\"\311\001\n\013ChatMessage\0227\n\007chann" +
      "el\030\001 \002(\0132&.tv.v1x1.common.dto.proto.core" +
      ".Channel\0223\n\006sender\030\002 \002(\0132#.tv.v1x1.commo" +
      "n.dto.proto.core.User\022\014\n\004text\030\003 \002(\t\022>\n\013p" +
      "ermissions\030\004 \003(\0132).tv.v1x1.common.dto.pr" +
      "oto.core.Permission"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          tv.v1x1.common.dto.proto.core.ChannelOuterClass.getDescriptor(),
          tv.v1x1.common.dto.proto.core.UserOuterClass.getDescriptor(),
          tv.v1x1.common.dto.proto.core.PermissionOuterClass.getDescriptor(),
        }, assigner);
    internal_static_tv_v1x1_common_dto_proto_core_ChatMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tv_v1x1_common_dto_proto_core_ChatMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tv_v1x1_common_dto_proto_core_ChatMessage_descriptor,
        new java.lang.String[] { "Channel", "Sender", "Text", "Permissions", });
    tv.v1x1.common.dto.proto.core.ChannelOuterClass.getDescriptor();
    tv.v1x1.common.dto.proto.core.UserOuterClass.getDescriptor();
    tv.v1x1.common.dto.proto.core.PermissionOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
