// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Module.proto

package tv.v1x1.common.dto.proto.core;

public final class ModuleOuterClass {
  private ModuleOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ModuleOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tv.v1x1.common.dto.proto.core.Module)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string name = 1;</code>
     */
    boolean hasName();
    /**
     * <code>required string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>required string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();
  }
  /**
   * Protobuf type {@code tv.v1x1.common.dto.proto.core.Module}
   */
  public  static final class Module extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tv.v1x1.common.dto.proto.core.Module)
      ModuleOrBuilder {
    // Use Module.newBuilder() to construct.
    private Module(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Module() {
      name_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Module(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              name_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return tv.v1x1.common.dto.proto.core.ModuleOuterClass.internal_static_tv_v1x1_common_dto_proto_core_Module_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return tv.v1x1.common.dto.proto.core.ModuleOuterClass.internal_static_tv_v1x1_common_dto_proto_core_Module_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              tv.v1x1.common.dto.proto.core.ModuleOuterClass.Module.class, tv.v1x1.common.dto.proto.core.ModuleOuterClass.Module.Builder.class);
    }

    private int bitField0_;
    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>required string name = 1;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof tv.v1x1.common.dto.proto.core.ModuleOuterClass.Module)) {
        return super.equals(obj);
      }
      tv.v1x1.common.dto.proto.core.ModuleOuterClass.Module other = (tv.v1x1.common.dto.proto.core.ModuleOuterClass.Module) obj;

      boolean result = true;
      result = result && (hasName() == other.hasName());
      if (hasName()) {
        result = result && getName()
            .equals(other.getName());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasName()) {
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static tv.v1x1.common.dto.proto.core.ModuleOuterClass.Module parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tv.v1x1.common.dto.proto.core.ModuleOuterClass.Module parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tv.v1x1.common.dto.proto.core.ModuleOuterClass.Module parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tv.v1x1.common.dto.proto.core.ModuleOuterClass.Module parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tv.v1x1.common.dto.proto.core.ModuleOuterClass.Module parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static tv.v1x1.common.dto.proto.core.ModuleOuterClass.Module parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static tv.v1x1.common.dto.proto.core.ModuleOuterClass.Module parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static tv.v1x1.common.dto.proto.core.ModuleOuterClass.Module parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static tv.v1x1.common.dto.proto.core.ModuleOuterClass.Module parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static tv.v1x1.common.dto.proto.core.ModuleOuterClass.Module parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(tv.v1x1.common.dto.proto.core.ModuleOuterClass.Module prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tv.v1x1.common.dto.proto.core.Module}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tv.v1x1.common.dto.proto.core.Module)
        tv.v1x1.common.dto.proto.core.ModuleOuterClass.ModuleOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return tv.v1x1.common.dto.proto.core.ModuleOuterClass.internal_static_tv_v1x1_common_dto_proto_core_Module_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return tv.v1x1.common.dto.proto.core.ModuleOuterClass.internal_static_tv_v1x1_common_dto_proto_core_Module_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                tv.v1x1.common.dto.proto.core.ModuleOuterClass.Module.class, tv.v1x1.common.dto.proto.core.ModuleOuterClass.Module.Builder.class);
      }

      // Construct using tv.v1x1.common.dto.proto.core.ModuleOuterClass.Module.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return tv.v1x1.common.dto.proto.core.ModuleOuterClass.internal_static_tv_v1x1_common_dto_proto_core_Module_descriptor;
      }

      public tv.v1x1.common.dto.proto.core.ModuleOuterClass.Module getDefaultInstanceForType() {
        return tv.v1x1.common.dto.proto.core.ModuleOuterClass.Module.getDefaultInstance();
      }

      public tv.v1x1.common.dto.proto.core.ModuleOuterClass.Module build() {
        tv.v1x1.common.dto.proto.core.ModuleOuterClass.Module result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public tv.v1x1.common.dto.proto.core.ModuleOuterClass.Module buildPartial() {
        tv.v1x1.common.dto.proto.core.ModuleOuterClass.Module result = new tv.v1x1.common.dto.proto.core.ModuleOuterClass.Module(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof tv.v1x1.common.dto.proto.core.ModuleOuterClass.Module) {
          return mergeFrom((tv.v1x1.common.dto.proto.core.ModuleOuterClass.Module)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(tv.v1x1.common.dto.proto.core.ModuleOuterClass.Module other) {
        if (other == tv.v1x1.common.dto.proto.core.ModuleOuterClass.Module.getDefaultInstance()) return this;
        if (other.hasName()) {
          bitField0_ |= 0x00000001;
          name_ = other.name_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasName()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        tv.v1x1.common.dto.proto.core.ModuleOuterClass.Module parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (tv.v1x1.common.dto.proto.core.ModuleOuterClass.Module) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object name_ = "";
      /**
       * <code>required string name = 1;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:tv.v1x1.common.dto.proto.core.Module)
    }

    // @@protoc_insertion_point(class_scope:tv.v1x1.common.dto.proto.core.Module)
    private static final tv.v1x1.common.dto.proto.core.ModuleOuterClass.Module DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new tv.v1x1.common.dto.proto.core.ModuleOuterClass.Module();
    }

    public static tv.v1x1.common.dto.proto.core.ModuleOuterClass.Module getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Module>
        PARSER = new com.google.protobuf.AbstractParser<Module>() {
      public Module parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Module(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Module> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Module> getParserForType() {
      return PARSER;
    }

    public tv.v1x1.common.dto.proto.core.ModuleOuterClass.Module getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ModuleInstanceOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tv.v1x1.common.dto.proto.core.ModuleInstance)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .tv.v1x1.common.dto.proto.core.UUID id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required .tv.v1x1.common.dto.proto.core.UUID id = 1;</code>
     */
    tv.v1x1.common.dto.proto.core.UUIDOuterClass.UUID getId();
    /**
     * <code>required .tv.v1x1.common.dto.proto.core.UUID id = 1;</code>
     */
    tv.v1x1.common.dto.proto.core.UUIDOuterClass.UUIDOrBuilder getIdOrBuilder();

    /**
     * <code>required .tv.v1x1.common.dto.proto.core.Module module = 2;</code>
     */
    boolean hasModule();
    /**
     * <code>required .tv.v1x1.common.dto.proto.core.Module module = 2;</code>
     */
    tv.v1x1.common.dto.proto.core.ModuleOuterClass.Module getModule();
    /**
     * <code>required .tv.v1x1.common.dto.proto.core.Module module = 2;</code>
     */
    tv.v1x1.common.dto.proto.core.ModuleOuterClass.ModuleOrBuilder getModuleOrBuilder();
  }
  /**
   * Protobuf type {@code tv.v1x1.common.dto.proto.core.ModuleInstance}
   */
  public  static final class ModuleInstance extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tv.v1x1.common.dto.proto.core.ModuleInstance)
      ModuleInstanceOrBuilder {
    // Use ModuleInstance.newBuilder() to construct.
    private ModuleInstance(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ModuleInstance() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ModuleInstance(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              tv.v1x1.common.dto.proto.core.UUIDOuterClass.UUID.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = id_.toBuilder();
              }
              id_ = input.readMessage(tv.v1x1.common.dto.proto.core.UUIDOuterClass.UUID.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(id_);
                id_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              tv.v1x1.common.dto.proto.core.ModuleOuterClass.Module.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = module_.toBuilder();
              }
              module_ = input.readMessage(tv.v1x1.common.dto.proto.core.ModuleOuterClass.Module.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(module_);
                module_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return tv.v1x1.common.dto.proto.core.ModuleOuterClass.internal_static_tv_v1x1_common_dto_proto_core_ModuleInstance_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return tv.v1x1.common.dto.proto.core.ModuleOuterClass.internal_static_tv_v1x1_common_dto_proto_core_ModuleInstance_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              tv.v1x1.common.dto.proto.core.ModuleOuterClass.ModuleInstance.class, tv.v1x1.common.dto.proto.core.ModuleOuterClass.ModuleInstance.Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private tv.v1x1.common.dto.proto.core.UUIDOuterClass.UUID id_;
    /**
     * <code>required .tv.v1x1.common.dto.proto.core.UUID id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .tv.v1x1.common.dto.proto.core.UUID id = 1;</code>
     */
    public tv.v1x1.common.dto.proto.core.UUIDOuterClass.UUID getId() {
      return id_ == null ? tv.v1x1.common.dto.proto.core.UUIDOuterClass.UUID.getDefaultInstance() : id_;
    }
    /**
     * <code>required .tv.v1x1.common.dto.proto.core.UUID id = 1;</code>
     */
    public tv.v1x1.common.dto.proto.core.UUIDOuterClass.UUIDOrBuilder getIdOrBuilder() {
      return id_ == null ? tv.v1x1.common.dto.proto.core.UUIDOuterClass.UUID.getDefaultInstance() : id_;
    }

    public static final int MODULE_FIELD_NUMBER = 2;
    private tv.v1x1.common.dto.proto.core.ModuleOuterClass.Module module_;
    /**
     * <code>required .tv.v1x1.common.dto.proto.core.Module module = 2;</code>
     */
    public boolean hasModule() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .tv.v1x1.common.dto.proto.core.Module module = 2;</code>
     */
    public tv.v1x1.common.dto.proto.core.ModuleOuterClass.Module getModule() {
      return module_ == null ? tv.v1x1.common.dto.proto.core.ModuleOuterClass.Module.getDefaultInstance() : module_;
    }
    /**
     * <code>required .tv.v1x1.common.dto.proto.core.Module module = 2;</code>
     */
    public tv.v1x1.common.dto.proto.core.ModuleOuterClass.ModuleOrBuilder getModuleOrBuilder() {
      return module_ == null ? tv.v1x1.common.dto.proto.core.ModuleOuterClass.Module.getDefaultInstance() : module_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasModule()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getId().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getModule().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, getId());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, getModule());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getId());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getModule());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof tv.v1x1.common.dto.proto.core.ModuleOuterClass.ModuleInstance)) {
        return super.equals(obj);
      }
      tv.v1x1.common.dto.proto.core.ModuleOuterClass.ModuleInstance other = (tv.v1x1.common.dto.proto.core.ModuleOuterClass.ModuleInstance) obj;

      boolean result = true;
      result = result && (hasId() == other.hasId());
      if (hasId()) {
        result = result && getId()
            .equals(other.getId());
      }
      result = result && (hasModule() == other.hasModule());
      if (hasModule()) {
        result = result && getModule()
            .equals(other.getModule());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasId()) {
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + getId().hashCode();
      }
      if (hasModule()) {
        hash = (37 * hash) + MODULE_FIELD_NUMBER;
        hash = (53 * hash) + getModule().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static tv.v1x1.common.dto.proto.core.ModuleOuterClass.ModuleInstance parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tv.v1x1.common.dto.proto.core.ModuleOuterClass.ModuleInstance parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tv.v1x1.common.dto.proto.core.ModuleOuterClass.ModuleInstance parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tv.v1x1.common.dto.proto.core.ModuleOuterClass.ModuleInstance parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tv.v1x1.common.dto.proto.core.ModuleOuterClass.ModuleInstance parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static tv.v1x1.common.dto.proto.core.ModuleOuterClass.ModuleInstance parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static tv.v1x1.common.dto.proto.core.ModuleOuterClass.ModuleInstance parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static tv.v1x1.common.dto.proto.core.ModuleOuterClass.ModuleInstance parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static tv.v1x1.common.dto.proto.core.ModuleOuterClass.ModuleInstance parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static tv.v1x1.common.dto.proto.core.ModuleOuterClass.ModuleInstance parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(tv.v1x1.common.dto.proto.core.ModuleOuterClass.ModuleInstance prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tv.v1x1.common.dto.proto.core.ModuleInstance}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tv.v1x1.common.dto.proto.core.ModuleInstance)
        tv.v1x1.common.dto.proto.core.ModuleOuterClass.ModuleInstanceOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return tv.v1x1.common.dto.proto.core.ModuleOuterClass.internal_static_tv_v1x1_common_dto_proto_core_ModuleInstance_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return tv.v1x1.common.dto.proto.core.ModuleOuterClass.internal_static_tv_v1x1_common_dto_proto_core_ModuleInstance_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                tv.v1x1.common.dto.proto.core.ModuleOuterClass.ModuleInstance.class, tv.v1x1.common.dto.proto.core.ModuleOuterClass.ModuleInstance.Builder.class);
      }

      // Construct using tv.v1x1.common.dto.proto.core.ModuleOuterClass.ModuleInstance.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getIdFieldBuilder();
          getModuleFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (idBuilder_ == null) {
          id_ = null;
        } else {
          idBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        if (moduleBuilder_ == null) {
          module_ = null;
        } else {
          moduleBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return tv.v1x1.common.dto.proto.core.ModuleOuterClass.internal_static_tv_v1x1_common_dto_proto_core_ModuleInstance_descriptor;
      }

      public tv.v1x1.common.dto.proto.core.ModuleOuterClass.ModuleInstance getDefaultInstanceForType() {
        return tv.v1x1.common.dto.proto.core.ModuleOuterClass.ModuleInstance.getDefaultInstance();
      }

      public tv.v1x1.common.dto.proto.core.ModuleOuterClass.ModuleInstance build() {
        tv.v1x1.common.dto.proto.core.ModuleOuterClass.ModuleInstance result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public tv.v1x1.common.dto.proto.core.ModuleOuterClass.ModuleInstance buildPartial() {
        tv.v1x1.common.dto.proto.core.ModuleOuterClass.ModuleInstance result = new tv.v1x1.common.dto.proto.core.ModuleOuterClass.ModuleInstance(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (idBuilder_ == null) {
          result.id_ = id_;
        } else {
          result.id_ = idBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (moduleBuilder_ == null) {
          result.module_ = module_;
        } else {
          result.module_ = moduleBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof tv.v1x1.common.dto.proto.core.ModuleOuterClass.ModuleInstance) {
          return mergeFrom((tv.v1x1.common.dto.proto.core.ModuleOuterClass.ModuleInstance)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(tv.v1x1.common.dto.proto.core.ModuleOuterClass.ModuleInstance other) {
        if (other == tv.v1x1.common.dto.proto.core.ModuleOuterClass.ModuleInstance.getDefaultInstance()) return this;
        if (other.hasId()) {
          mergeId(other.getId());
        }
        if (other.hasModule()) {
          mergeModule(other.getModule());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          return false;
        }
        if (!hasModule()) {
          return false;
        }
        if (!getId().isInitialized()) {
          return false;
        }
        if (!getModule().isInitialized()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        tv.v1x1.common.dto.proto.core.ModuleOuterClass.ModuleInstance parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (tv.v1x1.common.dto.proto.core.ModuleOuterClass.ModuleInstance) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private tv.v1x1.common.dto.proto.core.UUIDOuterClass.UUID id_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          tv.v1x1.common.dto.proto.core.UUIDOuterClass.UUID, tv.v1x1.common.dto.proto.core.UUIDOuterClass.UUID.Builder, tv.v1x1.common.dto.proto.core.UUIDOuterClass.UUIDOrBuilder> idBuilder_;
      /**
       * <code>required .tv.v1x1.common.dto.proto.core.UUID id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .tv.v1x1.common.dto.proto.core.UUID id = 1;</code>
       */
      public tv.v1x1.common.dto.proto.core.UUIDOuterClass.UUID getId() {
        if (idBuilder_ == null) {
          return id_ == null ? tv.v1x1.common.dto.proto.core.UUIDOuterClass.UUID.getDefaultInstance() : id_;
        } else {
          return idBuilder_.getMessage();
        }
      }
      /**
       * <code>required .tv.v1x1.common.dto.proto.core.UUID id = 1;</code>
       */
      public Builder setId(tv.v1x1.common.dto.proto.core.UUIDOuterClass.UUID value) {
        if (idBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          id_ = value;
          onChanged();
        } else {
          idBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .tv.v1x1.common.dto.proto.core.UUID id = 1;</code>
       */
      public Builder setId(
          tv.v1x1.common.dto.proto.core.UUIDOuterClass.UUID.Builder builderForValue) {
        if (idBuilder_ == null) {
          id_ = builderForValue.build();
          onChanged();
        } else {
          idBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .tv.v1x1.common.dto.proto.core.UUID id = 1;</code>
       */
      public Builder mergeId(tv.v1x1.common.dto.proto.core.UUIDOuterClass.UUID value) {
        if (idBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              id_ != null &&
              id_ != tv.v1x1.common.dto.proto.core.UUIDOuterClass.UUID.getDefaultInstance()) {
            id_ =
              tv.v1x1.common.dto.proto.core.UUIDOuterClass.UUID.newBuilder(id_).mergeFrom(value).buildPartial();
          } else {
            id_ = value;
          }
          onChanged();
        } else {
          idBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .tv.v1x1.common.dto.proto.core.UUID id = 1;</code>
       */
      public Builder clearId() {
        if (idBuilder_ == null) {
          id_ = null;
          onChanged();
        } else {
          idBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>required .tv.v1x1.common.dto.proto.core.UUID id = 1;</code>
       */
      public tv.v1x1.common.dto.proto.core.UUIDOuterClass.UUID.Builder getIdBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getIdFieldBuilder().getBuilder();
      }
      /**
       * <code>required .tv.v1x1.common.dto.proto.core.UUID id = 1;</code>
       */
      public tv.v1x1.common.dto.proto.core.UUIDOuterClass.UUIDOrBuilder getIdOrBuilder() {
        if (idBuilder_ != null) {
          return idBuilder_.getMessageOrBuilder();
        } else {
          return id_ == null ?
              tv.v1x1.common.dto.proto.core.UUIDOuterClass.UUID.getDefaultInstance() : id_;
        }
      }
      /**
       * <code>required .tv.v1x1.common.dto.proto.core.UUID id = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          tv.v1x1.common.dto.proto.core.UUIDOuterClass.UUID, tv.v1x1.common.dto.proto.core.UUIDOuterClass.UUID.Builder, tv.v1x1.common.dto.proto.core.UUIDOuterClass.UUIDOrBuilder> 
          getIdFieldBuilder() {
        if (idBuilder_ == null) {
          idBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              tv.v1x1.common.dto.proto.core.UUIDOuterClass.UUID, tv.v1x1.common.dto.proto.core.UUIDOuterClass.UUID.Builder, tv.v1x1.common.dto.proto.core.UUIDOuterClass.UUIDOrBuilder>(
                  getId(),
                  getParentForChildren(),
                  isClean());
          id_ = null;
        }
        return idBuilder_;
      }

      private tv.v1x1.common.dto.proto.core.ModuleOuterClass.Module module_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          tv.v1x1.common.dto.proto.core.ModuleOuterClass.Module, tv.v1x1.common.dto.proto.core.ModuleOuterClass.Module.Builder, tv.v1x1.common.dto.proto.core.ModuleOuterClass.ModuleOrBuilder> moduleBuilder_;
      /**
       * <code>required .tv.v1x1.common.dto.proto.core.Module module = 2;</code>
       */
      public boolean hasModule() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .tv.v1x1.common.dto.proto.core.Module module = 2;</code>
       */
      public tv.v1x1.common.dto.proto.core.ModuleOuterClass.Module getModule() {
        if (moduleBuilder_ == null) {
          return module_ == null ? tv.v1x1.common.dto.proto.core.ModuleOuterClass.Module.getDefaultInstance() : module_;
        } else {
          return moduleBuilder_.getMessage();
        }
      }
      /**
       * <code>required .tv.v1x1.common.dto.proto.core.Module module = 2;</code>
       */
      public Builder setModule(tv.v1x1.common.dto.proto.core.ModuleOuterClass.Module value) {
        if (moduleBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          module_ = value;
          onChanged();
        } else {
          moduleBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .tv.v1x1.common.dto.proto.core.Module module = 2;</code>
       */
      public Builder setModule(
          tv.v1x1.common.dto.proto.core.ModuleOuterClass.Module.Builder builderForValue) {
        if (moduleBuilder_ == null) {
          module_ = builderForValue.build();
          onChanged();
        } else {
          moduleBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .tv.v1x1.common.dto.proto.core.Module module = 2;</code>
       */
      public Builder mergeModule(tv.v1x1.common.dto.proto.core.ModuleOuterClass.Module value) {
        if (moduleBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              module_ != null &&
              module_ != tv.v1x1.common.dto.proto.core.ModuleOuterClass.Module.getDefaultInstance()) {
            module_ =
              tv.v1x1.common.dto.proto.core.ModuleOuterClass.Module.newBuilder(module_).mergeFrom(value).buildPartial();
          } else {
            module_ = value;
          }
          onChanged();
        } else {
          moduleBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .tv.v1x1.common.dto.proto.core.Module module = 2;</code>
       */
      public Builder clearModule() {
        if (moduleBuilder_ == null) {
          module_ = null;
          onChanged();
        } else {
          moduleBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>required .tv.v1x1.common.dto.proto.core.Module module = 2;</code>
       */
      public tv.v1x1.common.dto.proto.core.ModuleOuterClass.Module.Builder getModuleBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getModuleFieldBuilder().getBuilder();
      }
      /**
       * <code>required .tv.v1x1.common.dto.proto.core.Module module = 2;</code>
       */
      public tv.v1x1.common.dto.proto.core.ModuleOuterClass.ModuleOrBuilder getModuleOrBuilder() {
        if (moduleBuilder_ != null) {
          return moduleBuilder_.getMessageOrBuilder();
        } else {
          return module_ == null ?
              tv.v1x1.common.dto.proto.core.ModuleOuterClass.Module.getDefaultInstance() : module_;
        }
      }
      /**
       * <code>required .tv.v1x1.common.dto.proto.core.Module module = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          tv.v1x1.common.dto.proto.core.ModuleOuterClass.Module, tv.v1x1.common.dto.proto.core.ModuleOuterClass.Module.Builder, tv.v1x1.common.dto.proto.core.ModuleOuterClass.ModuleOrBuilder> 
          getModuleFieldBuilder() {
        if (moduleBuilder_ == null) {
          moduleBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              tv.v1x1.common.dto.proto.core.ModuleOuterClass.Module, tv.v1x1.common.dto.proto.core.ModuleOuterClass.Module.Builder, tv.v1x1.common.dto.proto.core.ModuleOuterClass.ModuleOrBuilder>(
                  getModule(),
                  getParentForChildren(),
                  isClean());
          module_ = null;
        }
        return moduleBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:tv.v1x1.common.dto.proto.core.ModuleInstance)
    }

    // @@protoc_insertion_point(class_scope:tv.v1x1.common.dto.proto.core.ModuleInstance)
    private static final tv.v1x1.common.dto.proto.core.ModuleOuterClass.ModuleInstance DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new tv.v1x1.common.dto.proto.core.ModuleOuterClass.ModuleInstance();
    }

    public static tv.v1x1.common.dto.proto.core.ModuleOuterClass.ModuleInstance getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<ModuleInstance>
        PARSER = new com.google.protobuf.AbstractParser<ModuleInstance>() {
      public ModuleInstance parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ModuleInstance(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ModuleInstance> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ModuleInstance> getParserForType() {
      return PARSER;
    }

    public tv.v1x1.common.dto.proto.core.ModuleOuterClass.ModuleInstance getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tv_v1x1_common_dto_proto_core_Module_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tv_v1x1_common_dto_proto_core_Module_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tv_v1x1_common_dto_proto_core_ModuleInstance_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tv_v1x1_common_dto_proto_core_ModuleInstance_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014Module.proto\022\035tv.v1x1.common.dto.proto" +
      ".core\032\nUUID.proto\"\026\n\006Module\022\014\n\004name\030\001 \002(" +
      "\t\"x\n\016ModuleInstance\022/\n\002id\030\001 \002(\0132#.tv.v1x" +
      "1.common.dto.proto.core.UUID\0225\n\006module\030\002" +
      " \002(\0132%.tv.v1x1.common.dto.proto.core.Mod" +
      "ule"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          tv.v1x1.common.dto.proto.core.UUIDOuterClass.getDescriptor(),
        }, assigner);
    internal_static_tv_v1x1_common_dto_proto_core_Module_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tv_v1x1_common_dto_proto_core_Module_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tv_v1x1_common_dto_proto_core_Module_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_tv_v1x1_common_dto_proto_core_ModuleInstance_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_tv_v1x1_common_dto_proto_core_ModuleInstance_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tv_v1x1_common_dto_proto_core_ModuleInstance_descriptor,
        new java.lang.String[] { "Id", "Module", });
    tv.v1x1.common.dto.proto.core.UUIDOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
