// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UUID.proto

package tv.v1x1.common.dto.proto.core;

public final class UUIDOuterClass {
  private UUIDOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface UUIDOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tv.v1x1.common.dto.proto.core.UUID)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required sfixed64 mostSignificantBits = 1;</code>
     */
    boolean hasMostSignificantBits();
    /**
     * <code>required sfixed64 mostSignificantBits = 1;</code>
     */
    long getMostSignificantBits();

    /**
     * <code>required sfixed64 leastSignificantBits = 2;</code>
     */
    boolean hasLeastSignificantBits();
    /**
     * <code>required sfixed64 leastSignificantBits = 2;</code>
     */
    long getLeastSignificantBits();
  }
  /**
   * Protobuf type {@code tv.v1x1.common.dto.proto.core.UUID}
   */
  public  static final class UUID extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tv.v1x1.common.dto.proto.core.UUID)
      UUIDOrBuilder {
    // Use UUID.newBuilder() to construct.
    private UUID(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UUID() {
      mostSignificantBits_ = 0L;
      leastSignificantBits_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private UUID(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 9: {
              bitField0_ |= 0x00000001;
              mostSignificantBits_ = input.readSFixed64();
              break;
            }
            case 17: {
              bitField0_ |= 0x00000002;
              leastSignificantBits_ = input.readSFixed64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return tv.v1x1.common.dto.proto.core.UUIDOuterClass.internal_static_tv_v1x1_common_dto_proto_core_UUID_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return tv.v1x1.common.dto.proto.core.UUIDOuterClass.internal_static_tv_v1x1_common_dto_proto_core_UUID_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              tv.v1x1.common.dto.proto.core.UUIDOuterClass.UUID.class, tv.v1x1.common.dto.proto.core.UUIDOuterClass.UUID.Builder.class);
    }

    private int bitField0_;
    public static final int MOSTSIGNIFICANTBITS_FIELD_NUMBER = 1;
    private long mostSignificantBits_;
    /**
     * <code>required sfixed64 mostSignificantBits = 1;</code>
     */
    public boolean hasMostSignificantBits() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required sfixed64 mostSignificantBits = 1;</code>
     */
    public long getMostSignificantBits() {
      return mostSignificantBits_;
    }

    public static final int LEASTSIGNIFICANTBITS_FIELD_NUMBER = 2;
    private long leastSignificantBits_;
    /**
     * <code>required sfixed64 leastSignificantBits = 2;</code>
     */
    public boolean hasLeastSignificantBits() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required sfixed64 leastSignificantBits = 2;</code>
     */
    public long getLeastSignificantBits() {
      return leastSignificantBits_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasMostSignificantBits()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLeastSignificantBits()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeSFixed64(1, mostSignificantBits_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeSFixed64(2, leastSignificantBits_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeSFixed64Size(1, mostSignificantBits_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeSFixed64Size(2, leastSignificantBits_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof tv.v1x1.common.dto.proto.core.UUIDOuterClass.UUID)) {
        return super.equals(obj);
      }
      tv.v1x1.common.dto.proto.core.UUIDOuterClass.UUID other = (tv.v1x1.common.dto.proto.core.UUIDOuterClass.UUID) obj;

      boolean result = true;
      result = result && (hasMostSignificantBits() == other.hasMostSignificantBits());
      if (hasMostSignificantBits()) {
        result = result && (getMostSignificantBits()
            == other.getMostSignificantBits());
      }
      result = result && (hasLeastSignificantBits() == other.hasLeastSignificantBits());
      if (hasLeastSignificantBits()) {
        result = result && (getLeastSignificantBits()
            == other.getLeastSignificantBits());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasMostSignificantBits()) {
        hash = (37 * hash) + MOSTSIGNIFICANTBITS_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getMostSignificantBits());
      }
      if (hasLeastSignificantBits()) {
        hash = (37 * hash) + LEASTSIGNIFICANTBITS_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getLeastSignificantBits());
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static tv.v1x1.common.dto.proto.core.UUIDOuterClass.UUID parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tv.v1x1.common.dto.proto.core.UUIDOuterClass.UUID parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tv.v1x1.common.dto.proto.core.UUIDOuterClass.UUID parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tv.v1x1.common.dto.proto.core.UUIDOuterClass.UUID parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tv.v1x1.common.dto.proto.core.UUIDOuterClass.UUID parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static tv.v1x1.common.dto.proto.core.UUIDOuterClass.UUID parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static tv.v1x1.common.dto.proto.core.UUIDOuterClass.UUID parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static tv.v1x1.common.dto.proto.core.UUIDOuterClass.UUID parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static tv.v1x1.common.dto.proto.core.UUIDOuterClass.UUID parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static tv.v1x1.common.dto.proto.core.UUIDOuterClass.UUID parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(tv.v1x1.common.dto.proto.core.UUIDOuterClass.UUID prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tv.v1x1.common.dto.proto.core.UUID}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tv.v1x1.common.dto.proto.core.UUID)
        tv.v1x1.common.dto.proto.core.UUIDOuterClass.UUIDOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return tv.v1x1.common.dto.proto.core.UUIDOuterClass.internal_static_tv_v1x1_common_dto_proto_core_UUID_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return tv.v1x1.common.dto.proto.core.UUIDOuterClass.internal_static_tv_v1x1_common_dto_proto_core_UUID_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                tv.v1x1.common.dto.proto.core.UUIDOuterClass.UUID.class, tv.v1x1.common.dto.proto.core.UUIDOuterClass.UUID.Builder.class);
      }

      // Construct using tv.v1x1.common.dto.proto.core.UUIDOuterClass.UUID.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        mostSignificantBits_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        leastSignificantBits_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return tv.v1x1.common.dto.proto.core.UUIDOuterClass.internal_static_tv_v1x1_common_dto_proto_core_UUID_descriptor;
      }

      public tv.v1x1.common.dto.proto.core.UUIDOuterClass.UUID getDefaultInstanceForType() {
        return tv.v1x1.common.dto.proto.core.UUIDOuterClass.UUID.getDefaultInstance();
      }

      public tv.v1x1.common.dto.proto.core.UUIDOuterClass.UUID build() {
        tv.v1x1.common.dto.proto.core.UUIDOuterClass.UUID result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public tv.v1x1.common.dto.proto.core.UUIDOuterClass.UUID buildPartial() {
        tv.v1x1.common.dto.proto.core.UUIDOuterClass.UUID result = new tv.v1x1.common.dto.proto.core.UUIDOuterClass.UUID(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.mostSignificantBits_ = mostSignificantBits_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.leastSignificantBits_ = leastSignificantBits_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof tv.v1x1.common.dto.proto.core.UUIDOuterClass.UUID) {
          return mergeFrom((tv.v1x1.common.dto.proto.core.UUIDOuterClass.UUID)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(tv.v1x1.common.dto.proto.core.UUIDOuterClass.UUID other) {
        if (other == tv.v1x1.common.dto.proto.core.UUIDOuterClass.UUID.getDefaultInstance()) return this;
        if (other.hasMostSignificantBits()) {
          setMostSignificantBits(other.getMostSignificantBits());
        }
        if (other.hasLeastSignificantBits()) {
          setLeastSignificantBits(other.getLeastSignificantBits());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasMostSignificantBits()) {
          return false;
        }
        if (!hasLeastSignificantBits()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        tv.v1x1.common.dto.proto.core.UUIDOuterClass.UUID parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (tv.v1x1.common.dto.proto.core.UUIDOuterClass.UUID) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long mostSignificantBits_ ;
      /**
       * <code>required sfixed64 mostSignificantBits = 1;</code>
       */
      public boolean hasMostSignificantBits() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required sfixed64 mostSignificantBits = 1;</code>
       */
      public long getMostSignificantBits() {
        return mostSignificantBits_;
      }
      /**
       * <code>required sfixed64 mostSignificantBits = 1;</code>
       */
      public Builder setMostSignificantBits(long value) {
        bitField0_ |= 0x00000001;
        mostSignificantBits_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required sfixed64 mostSignificantBits = 1;</code>
       */
      public Builder clearMostSignificantBits() {
        bitField0_ = (bitField0_ & ~0x00000001);
        mostSignificantBits_ = 0L;
        onChanged();
        return this;
      }

      private long leastSignificantBits_ ;
      /**
       * <code>required sfixed64 leastSignificantBits = 2;</code>
       */
      public boolean hasLeastSignificantBits() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required sfixed64 leastSignificantBits = 2;</code>
       */
      public long getLeastSignificantBits() {
        return leastSignificantBits_;
      }
      /**
       * <code>required sfixed64 leastSignificantBits = 2;</code>
       */
      public Builder setLeastSignificantBits(long value) {
        bitField0_ |= 0x00000002;
        leastSignificantBits_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required sfixed64 leastSignificantBits = 2;</code>
       */
      public Builder clearLeastSignificantBits() {
        bitField0_ = (bitField0_ & ~0x00000002);
        leastSignificantBits_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:tv.v1x1.common.dto.proto.core.UUID)
    }

    // @@protoc_insertion_point(class_scope:tv.v1x1.common.dto.proto.core.UUID)
    private static final tv.v1x1.common.dto.proto.core.UUIDOuterClass.UUID DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new tv.v1x1.common.dto.proto.core.UUIDOuterClass.UUID();
    }

    public static tv.v1x1.common.dto.proto.core.UUIDOuterClass.UUID getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<UUID>
        PARSER = new com.google.protobuf.AbstractParser<UUID>() {
      public UUID parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new UUID(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UUID> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UUID> getParserForType() {
      return PARSER;
    }

    public tv.v1x1.common.dto.proto.core.UUIDOuterClass.UUID getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tv_v1x1_common_dto_proto_core_UUID_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tv_v1x1_common_dto_proto_core_UUID_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nUUID.proto\022\035tv.v1x1.common.dto.proto.c" +
      "ore\"A\n\004UUID\022\033\n\023mostSignificantBits\030\001 \002(\020" +
      "\022\034\n\024leastSignificantBits\030\002 \002(\020"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_tv_v1x1_common_dto_proto_core_UUID_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tv_v1x1_common_dto_proto_core_UUID_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tv_v1x1_common_dto_proto_core_UUID_descriptor,
        new java.lang.String[] { "MostSignificantBits", "LeastSignificantBits", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
