// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Event.proto

package tv.twitchbot.common.dto.proto.messages;

public final class EventOuterClass {
  private EventOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
    registry.add(tv.twitchbot.common.dto.proto.messages.EventOuterClass.Event.data);
    registry.add(tv.twitchbot.common.dto.proto.messages.EventOuterClass.ChatMessageEvent.data);
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface EventOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tv.twitchbot.common.dto.proto.messages.Event)
      com.google.protobuf.GeneratedMessageV3.
          ExtendableMessageOrBuilder<Event> {

    /**
     * <code>required .tv.twitchbot.common.dto.proto.messages.Event.EventType type = 1;</code>
     */
    boolean hasType();
    /**
     * <code>required .tv.twitchbot.common.dto.proto.messages.Event.EventType type = 1;</code>
     */
    tv.twitchbot.common.dto.proto.messages.EventOuterClass.Event.EventType getType();
  }
  /**
   * Protobuf type {@code tv.twitchbot.common.dto.proto.messages.Event}
   */
  public  static final class Event extends
      com.google.protobuf.GeneratedMessageV3.ExtendableMessage<
        Event> implements
      // @@protoc_insertion_point(message_implements:tv.twitchbot.common.dto.proto.messages.Event)
      EventOrBuilder {
    // Use Event.newBuilder() to construct.
    private Event(com.google.protobuf.GeneratedMessageV3.ExtendableBuilder<tv.twitchbot.common.dto.proto.messages.EventOuterClass.Event, ?> builder) {
      super(builder);
    }
    private Event() {
      type_ = 1;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Event(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              tv.twitchbot.common.dto.proto.messages.EventOuterClass.Event.EventType value = tv.twitchbot.common.dto.proto.messages.EventOuterClass.Event.EventType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = rawValue;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return tv.twitchbot.common.dto.proto.messages.EventOuterClass.internal_static_tv_twitchbot_common_dto_proto_messages_Event_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return tv.twitchbot.common.dto.proto.messages.EventOuterClass.internal_static_tv_twitchbot_common_dto_proto_messages_Event_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              tv.twitchbot.common.dto.proto.messages.EventOuterClass.Event.class, tv.twitchbot.common.dto.proto.messages.EventOuterClass.Event.Builder.class);
    }

    /**
     * Protobuf enum {@code tv.twitchbot.common.dto.proto.messages.Event.EventType}
     */
    public enum EventType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>CHAT_MESSAGE = 1;</code>
       */
      CHAT_MESSAGE(1),
      ;

      /**
       * <code>CHAT_MESSAGE = 1;</code>
       */
      public static final int CHAT_MESSAGE_VALUE = 1;


      public final int getNumber() {
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static EventType valueOf(int value) {
        return forNumber(value);
      }

      public static EventType forNumber(int value) {
        switch (value) {
          case 1: return CHAT_MESSAGE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<EventType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          EventType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<EventType>() {
              public EventType findValueByNumber(int number) {
                return EventType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return tv.twitchbot.common.dto.proto.messages.EventOuterClass.Event.getDescriptor().getEnumTypes().get(0);
      }

      private static final EventType[] VALUES = values();

      public static EventType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private EventType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:tv.twitchbot.common.dto.proto.messages.Event.EventType)
    }

    private int bitField0_;
    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>required .tv.twitchbot.common.dto.proto.messages.Event.EventType type = 1;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .tv.twitchbot.common.dto.proto.messages.Event.EventType type = 1;</code>
     */
    public tv.twitchbot.common.dto.proto.messages.EventOuterClass.Event.EventType getType() {
      tv.twitchbot.common.dto.proto.messages.EventOuterClass.Event.EventType result = tv.twitchbot.common.dto.proto.messages.EventOuterClass.Event.EventType.valueOf(type_);
      return result == null ? tv.twitchbot.common.dto.proto.messages.EventOuterClass.Event.EventType.CHAT_MESSAGE : result;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!extensionsAreInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      com.google.protobuf.GeneratedMessageV3
        .ExtendableMessage<tv.twitchbot.common.dto.proto.messages.EventOuterClass.Event>.ExtensionWriter
          extensionWriter = newExtensionWriter();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_);
      }
      extensionWriter.writeUntil(536870912, output);
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_);
      }
      size += extensionsSerializedSize();
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof tv.twitchbot.common.dto.proto.messages.EventOuterClass.Event)) {
        return super.equals(obj);
      }
      tv.twitchbot.common.dto.proto.messages.EventOuterClass.Event other = (tv.twitchbot.common.dto.proto.messages.EventOuterClass.Event) obj;

      boolean result = true;
      result = result && (hasType() == other.hasType());
      if (hasType()) {
        result = result && type_ == other.type_;
      }
      result = result && unknownFields.equals(other.unknownFields);
      result = result &&
          getExtensionFields().equals(other.getExtensionFields());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasType()) {
        hash = (37 * hash) + TYPE_FIELD_NUMBER;
        hash = (53 * hash) + type_;
      }
      hash = hashFields(hash, getExtensionFields());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static tv.twitchbot.common.dto.proto.messages.EventOuterClass.Event parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tv.twitchbot.common.dto.proto.messages.EventOuterClass.Event parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tv.twitchbot.common.dto.proto.messages.EventOuterClass.Event parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tv.twitchbot.common.dto.proto.messages.EventOuterClass.Event parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tv.twitchbot.common.dto.proto.messages.EventOuterClass.Event parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static tv.twitchbot.common.dto.proto.messages.EventOuterClass.Event parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static tv.twitchbot.common.dto.proto.messages.EventOuterClass.Event parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static tv.twitchbot.common.dto.proto.messages.EventOuterClass.Event parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static tv.twitchbot.common.dto.proto.messages.EventOuterClass.Event parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static tv.twitchbot.common.dto.proto.messages.EventOuterClass.Event parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(tv.twitchbot.common.dto.proto.messages.EventOuterClass.Event prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tv.twitchbot.common.dto.proto.messages.Event}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.ExtendableBuilder<
          tv.twitchbot.common.dto.proto.messages.EventOuterClass.Event, Builder> implements
        // @@protoc_insertion_point(builder_implements:tv.twitchbot.common.dto.proto.messages.Event)
        tv.twitchbot.common.dto.proto.messages.EventOuterClass.EventOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return tv.twitchbot.common.dto.proto.messages.EventOuterClass.internal_static_tv_twitchbot_common_dto_proto_messages_Event_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return tv.twitchbot.common.dto.proto.messages.EventOuterClass.internal_static_tv_twitchbot_common_dto_proto_messages_Event_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                tv.twitchbot.common.dto.proto.messages.EventOuterClass.Event.class, tv.twitchbot.common.dto.proto.messages.EventOuterClass.Event.Builder.class);
      }

      // Construct using tv.twitchbot.common.dto.proto.messages.EventOuterClass.Event.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        type_ = 1;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return tv.twitchbot.common.dto.proto.messages.EventOuterClass.internal_static_tv_twitchbot_common_dto_proto_messages_Event_descriptor;
      }

      public tv.twitchbot.common.dto.proto.messages.EventOuterClass.Event getDefaultInstanceForType() {
        return tv.twitchbot.common.dto.proto.messages.EventOuterClass.Event.getDefaultInstance();
      }

      public tv.twitchbot.common.dto.proto.messages.EventOuterClass.Event build() {
        tv.twitchbot.common.dto.proto.messages.EventOuterClass.Event result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public tv.twitchbot.common.dto.proto.messages.EventOuterClass.Event buildPartial() {
        tv.twitchbot.common.dto.proto.messages.EventOuterClass.Event result = new tv.twitchbot.common.dto.proto.messages.EventOuterClass.Event(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public <Type> Builder setExtension(
          com.google.protobuf.GeneratedMessage.GeneratedExtension<
              tv.twitchbot.common.dto.proto.messages.EventOuterClass.Event, Type> extension,
          Type value) {
        return (Builder) super.setExtension(extension, value);
      }
      public <Type> Builder setExtension(
          com.google.protobuf.GeneratedMessage.GeneratedExtension<
              tv.twitchbot.common.dto.proto.messages.EventOuterClass.Event, java.util.List<Type>> extension,
          int index, Type value) {
        return (Builder) super.setExtension(extension, index, value);
      }
      public <Type> Builder addExtension(
          com.google.protobuf.GeneratedMessage.GeneratedExtension<
              tv.twitchbot.common.dto.proto.messages.EventOuterClass.Event, java.util.List<Type>> extension,
          Type value) {
        return (Builder) super.addExtension(extension, value);
      }
      public <Type> Builder clearExtension(
          com.google.protobuf.GeneratedMessage.GeneratedExtension<
              tv.twitchbot.common.dto.proto.messages.EventOuterClass.Event, ?> extension) {
        return (Builder) super.clearExtension(extension);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof tv.twitchbot.common.dto.proto.messages.EventOuterClass.Event) {
          return mergeFrom((tv.twitchbot.common.dto.proto.messages.EventOuterClass.Event)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(tv.twitchbot.common.dto.proto.messages.EventOuterClass.Event other) {
        if (other == tv.twitchbot.common.dto.proto.messages.EventOuterClass.Event.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        this.mergeExtensionFields(other);
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasType()) {
          return false;
        }
        if (!extensionsAreInitialized()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        tv.twitchbot.common.dto.proto.messages.EventOuterClass.Event parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (tv.twitchbot.common.dto.proto.messages.EventOuterClass.Event) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int type_ = 1;
      /**
       * <code>required .tv.twitchbot.common.dto.proto.messages.Event.EventType type = 1;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .tv.twitchbot.common.dto.proto.messages.Event.EventType type = 1;</code>
       */
      public tv.twitchbot.common.dto.proto.messages.EventOuterClass.Event.EventType getType() {
        tv.twitchbot.common.dto.proto.messages.EventOuterClass.Event.EventType result = tv.twitchbot.common.dto.proto.messages.EventOuterClass.Event.EventType.valueOf(type_);
        return result == null ? tv.twitchbot.common.dto.proto.messages.EventOuterClass.Event.EventType.CHAT_MESSAGE : result;
      }
      /**
       * <code>required .tv.twitchbot.common.dto.proto.messages.Event.EventType type = 1;</code>
       */
      public Builder setType(tv.twitchbot.common.dto.proto.messages.EventOuterClass.Event.EventType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>required .tv.twitchbot.common.dto.proto.messages.Event.EventType type = 1;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = 1;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:tv.twitchbot.common.dto.proto.messages.Event)
    }

    // @@protoc_insertion_point(class_scope:tv.twitchbot.common.dto.proto.messages.Event)
    private static final tv.twitchbot.common.dto.proto.messages.EventOuterClass.Event DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new tv.twitchbot.common.dto.proto.messages.EventOuterClass.Event();
    }

    public static tv.twitchbot.common.dto.proto.messages.EventOuterClass.Event getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Event>
        PARSER = new com.google.protobuf.AbstractParser<Event>() {
      public Event parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Event(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Event> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Event> getParserForType() {
      return PARSER;
    }

    public tv.twitchbot.common.dto.proto.messages.EventOuterClass.Event getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

    public static final int DATA_FIELD_NUMBER = 101;
    /**
     * <code>extend .tv.twitchbot.common.dto.proto.messages.Message { ... }</code>
     */
    public static final
      com.google.protobuf.GeneratedMessage.GeneratedExtension<
        tv.twitchbot.common.dto.proto.messages.MessageOuterClass.Message,
        tv.twitchbot.common.dto.proto.messages.EventOuterClass.Event> data = com.google.protobuf.GeneratedMessage
            .newMessageScopedGeneratedExtension(
          tv.twitchbot.common.dto.proto.messages.EventOuterClass.Event.getDefaultInstance(),
          0,
          tv.twitchbot.common.dto.proto.messages.EventOuterClass.Event.class,
          tv.twitchbot.common.dto.proto.messages.EventOuterClass.Event.getDefaultInstance());
  }

  public interface ChatMessageEventOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tv.twitchbot.common.dto.proto.messages.ChatMessageEvent)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .tv.twitchbot.common.dto.proto.core.ChatMessage chat_message = 1;</code>
     */
    boolean hasChatMessage();
    /**
     * <code>required .tv.twitchbot.common.dto.proto.core.ChatMessage chat_message = 1;</code>
     */
    tv.twitchbot.common.dto.proto.core.ChatMessageOuterClass.ChatMessage getChatMessage();
    /**
     * <code>required .tv.twitchbot.common.dto.proto.core.ChatMessage chat_message = 1;</code>
     */
    tv.twitchbot.common.dto.proto.core.ChatMessageOuterClass.ChatMessageOrBuilder getChatMessageOrBuilder();
  }
  /**
   * Protobuf type {@code tv.twitchbot.common.dto.proto.messages.ChatMessageEvent}
   */
  public  static final class ChatMessageEvent extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tv.twitchbot.common.dto.proto.messages.ChatMessageEvent)
      ChatMessageEventOrBuilder {
    // Use ChatMessageEvent.newBuilder() to construct.
    private ChatMessageEvent(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ChatMessageEvent() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ChatMessageEvent(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              tv.twitchbot.common.dto.proto.core.ChatMessageOuterClass.ChatMessage.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = chatMessage_.toBuilder();
              }
              chatMessage_ = input.readMessage(tv.twitchbot.common.dto.proto.core.ChatMessageOuterClass.ChatMessage.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(chatMessage_);
                chatMessage_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return tv.twitchbot.common.dto.proto.messages.EventOuterClass.internal_static_tv_twitchbot_common_dto_proto_messages_ChatMessageEvent_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return tv.twitchbot.common.dto.proto.messages.EventOuterClass.internal_static_tv_twitchbot_common_dto_proto_messages_ChatMessageEvent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              tv.twitchbot.common.dto.proto.messages.EventOuterClass.ChatMessageEvent.class, tv.twitchbot.common.dto.proto.messages.EventOuterClass.ChatMessageEvent.Builder.class);
    }

    private int bitField0_;
    public static final int CHAT_MESSAGE_FIELD_NUMBER = 1;
    private tv.twitchbot.common.dto.proto.core.ChatMessageOuterClass.ChatMessage chatMessage_;
    /**
     * <code>required .tv.twitchbot.common.dto.proto.core.ChatMessage chat_message = 1;</code>
     */
    public boolean hasChatMessage() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .tv.twitchbot.common.dto.proto.core.ChatMessage chat_message = 1;</code>
     */
    public tv.twitchbot.common.dto.proto.core.ChatMessageOuterClass.ChatMessage getChatMessage() {
      return chatMessage_ == null ? tv.twitchbot.common.dto.proto.core.ChatMessageOuterClass.ChatMessage.getDefaultInstance() : chatMessage_;
    }
    /**
     * <code>required .tv.twitchbot.common.dto.proto.core.ChatMessage chat_message = 1;</code>
     */
    public tv.twitchbot.common.dto.proto.core.ChatMessageOuterClass.ChatMessageOrBuilder getChatMessageOrBuilder() {
      return chatMessage_ == null ? tv.twitchbot.common.dto.proto.core.ChatMessageOuterClass.ChatMessage.getDefaultInstance() : chatMessage_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasChatMessage()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getChatMessage().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, getChatMessage());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getChatMessage());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof tv.twitchbot.common.dto.proto.messages.EventOuterClass.ChatMessageEvent)) {
        return super.equals(obj);
      }
      tv.twitchbot.common.dto.proto.messages.EventOuterClass.ChatMessageEvent other = (tv.twitchbot.common.dto.proto.messages.EventOuterClass.ChatMessageEvent) obj;

      boolean result = true;
      result = result && (hasChatMessage() == other.hasChatMessage());
      if (hasChatMessage()) {
        result = result && getChatMessage()
            .equals(other.getChatMessage());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasChatMessage()) {
        hash = (37 * hash) + CHAT_MESSAGE_FIELD_NUMBER;
        hash = (53 * hash) + getChatMessage().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static tv.twitchbot.common.dto.proto.messages.EventOuterClass.ChatMessageEvent parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tv.twitchbot.common.dto.proto.messages.EventOuterClass.ChatMessageEvent parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tv.twitchbot.common.dto.proto.messages.EventOuterClass.ChatMessageEvent parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tv.twitchbot.common.dto.proto.messages.EventOuterClass.ChatMessageEvent parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tv.twitchbot.common.dto.proto.messages.EventOuterClass.ChatMessageEvent parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static tv.twitchbot.common.dto.proto.messages.EventOuterClass.ChatMessageEvent parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static tv.twitchbot.common.dto.proto.messages.EventOuterClass.ChatMessageEvent parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static tv.twitchbot.common.dto.proto.messages.EventOuterClass.ChatMessageEvent parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static tv.twitchbot.common.dto.proto.messages.EventOuterClass.ChatMessageEvent parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static tv.twitchbot.common.dto.proto.messages.EventOuterClass.ChatMessageEvent parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(tv.twitchbot.common.dto.proto.messages.EventOuterClass.ChatMessageEvent prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tv.twitchbot.common.dto.proto.messages.ChatMessageEvent}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tv.twitchbot.common.dto.proto.messages.ChatMessageEvent)
        tv.twitchbot.common.dto.proto.messages.EventOuterClass.ChatMessageEventOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return tv.twitchbot.common.dto.proto.messages.EventOuterClass.internal_static_tv_twitchbot_common_dto_proto_messages_ChatMessageEvent_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return tv.twitchbot.common.dto.proto.messages.EventOuterClass.internal_static_tv_twitchbot_common_dto_proto_messages_ChatMessageEvent_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                tv.twitchbot.common.dto.proto.messages.EventOuterClass.ChatMessageEvent.class, tv.twitchbot.common.dto.proto.messages.EventOuterClass.ChatMessageEvent.Builder.class);
      }

      // Construct using tv.twitchbot.common.dto.proto.messages.EventOuterClass.ChatMessageEvent.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getChatMessageFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (chatMessageBuilder_ == null) {
          chatMessage_ = null;
        } else {
          chatMessageBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return tv.twitchbot.common.dto.proto.messages.EventOuterClass.internal_static_tv_twitchbot_common_dto_proto_messages_ChatMessageEvent_descriptor;
      }

      public tv.twitchbot.common.dto.proto.messages.EventOuterClass.ChatMessageEvent getDefaultInstanceForType() {
        return tv.twitchbot.common.dto.proto.messages.EventOuterClass.ChatMessageEvent.getDefaultInstance();
      }

      public tv.twitchbot.common.dto.proto.messages.EventOuterClass.ChatMessageEvent build() {
        tv.twitchbot.common.dto.proto.messages.EventOuterClass.ChatMessageEvent result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public tv.twitchbot.common.dto.proto.messages.EventOuterClass.ChatMessageEvent buildPartial() {
        tv.twitchbot.common.dto.proto.messages.EventOuterClass.ChatMessageEvent result = new tv.twitchbot.common.dto.proto.messages.EventOuterClass.ChatMessageEvent(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (chatMessageBuilder_ == null) {
          result.chatMessage_ = chatMessage_;
        } else {
          result.chatMessage_ = chatMessageBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof tv.twitchbot.common.dto.proto.messages.EventOuterClass.ChatMessageEvent) {
          return mergeFrom((tv.twitchbot.common.dto.proto.messages.EventOuterClass.ChatMessageEvent)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(tv.twitchbot.common.dto.proto.messages.EventOuterClass.ChatMessageEvent other) {
        if (other == tv.twitchbot.common.dto.proto.messages.EventOuterClass.ChatMessageEvent.getDefaultInstance()) return this;
        if (other.hasChatMessage()) {
          mergeChatMessage(other.getChatMessage());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasChatMessage()) {
          return false;
        }
        if (!getChatMessage().isInitialized()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        tv.twitchbot.common.dto.proto.messages.EventOuterClass.ChatMessageEvent parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (tv.twitchbot.common.dto.proto.messages.EventOuterClass.ChatMessageEvent) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private tv.twitchbot.common.dto.proto.core.ChatMessageOuterClass.ChatMessage chatMessage_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          tv.twitchbot.common.dto.proto.core.ChatMessageOuterClass.ChatMessage, tv.twitchbot.common.dto.proto.core.ChatMessageOuterClass.ChatMessage.Builder, tv.twitchbot.common.dto.proto.core.ChatMessageOuterClass.ChatMessageOrBuilder> chatMessageBuilder_;
      /**
       * <code>required .tv.twitchbot.common.dto.proto.core.ChatMessage chat_message = 1;</code>
       */
      public boolean hasChatMessage() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .tv.twitchbot.common.dto.proto.core.ChatMessage chat_message = 1;</code>
       */
      public tv.twitchbot.common.dto.proto.core.ChatMessageOuterClass.ChatMessage getChatMessage() {
        if (chatMessageBuilder_ == null) {
          return chatMessage_ == null ? tv.twitchbot.common.dto.proto.core.ChatMessageOuterClass.ChatMessage.getDefaultInstance() : chatMessage_;
        } else {
          return chatMessageBuilder_.getMessage();
        }
      }
      /**
       * <code>required .tv.twitchbot.common.dto.proto.core.ChatMessage chat_message = 1;</code>
       */
      public Builder setChatMessage(tv.twitchbot.common.dto.proto.core.ChatMessageOuterClass.ChatMessage value) {
        if (chatMessageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          chatMessage_ = value;
          onChanged();
        } else {
          chatMessageBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .tv.twitchbot.common.dto.proto.core.ChatMessage chat_message = 1;</code>
       */
      public Builder setChatMessage(
          tv.twitchbot.common.dto.proto.core.ChatMessageOuterClass.ChatMessage.Builder builderForValue) {
        if (chatMessageBuilder_ == null) {
          chatMessage_ = builderForValue.build();
          onChanged();
        } else {
          chatMessageBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .tv.twitchbot.common.dto.proto.core.ChatMessage chat_message = 1;</code>
       */
      public Builder mergeChatMessage(tv.twitchbot.common.dto.proto.core.ChatMessageOuterClass.ChatMessage value) {
        if (chatMessageBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              chatMessage_ != null &&
              chatMessage_ != tv.twitchbot.common.dto.proto.core.ChatMessageOuterClass.ChatMessage.getDefaultInstance()) {
            chatMessage_ =
              tv.twitchbot.common.dto.proto.core.ChatMessageOuterClass.ChatMessage.newBuilder(chatMessage_).mergeFrom(value).buildPartial();
          } else {
            chatMessage_ = value;
          }
          onChanged();
        } else {
          chatMessageBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .tv.twitchbot.common.dto.proto.core.ChatMessage chat_message = 1;</code>
       */
      public Builder clearChatMessage() {
        if (chatMessageBuilder_ == null) {
          chatMessage_ = null;
          onChanged();
        } else {
          chatMessageBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>required .tv.twitchbot.common.dto.proto.core.ChatMessage chat_message = 1;</code>
       */
      public tv.twitchbot.common.dto.proto.core.ChatMessageOuterClass.ChatMessage.Builder getChatMessageBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getChatMessageFieldBuilder().getBuilder();
      }
      /**
       * <code>required .tv.twitchbot.common.dto.proto.core.ChatMessage chat_message = 1;</code>
       */
      public tv.twitchbot.common.dto.proto.core.ChatMessageOuterClass.ChatMessageOrBuilder getChatMessageOrBuilder() {
        if (chatMessageBuilder_ != null) {
          return chatMessageBuilder_.getMessageOrBuilder();
        } else {
          return chatMessage_ == null ?
              tv.twitchbot.common.dto.proto.core.ChatMessageOuterClass.ChatMessage.getDefaultInstance() : chatMessage_;
        }
      }
      /**
       * <code>required .tv.twitchbot.common.dto.proto.core.ChatMessage chat_message = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          tv.twitchbot.common.dto.proto.core.ChatMessageOuterClass.ChatMessage, tv.twitchbot.common.dto.proto.core.ChatMessageOuterClass.ChatMessage.Builder, tv.twitchbot.common.dto.proto.core.ChatMessageOuterClass.ChatMessageOrBuilder> 
          getChatMessageFieldBuilder() {
        if (chatMessageBuilder_ == null) {
          chatMessageBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              tv.twitchbot.common.dto.proto.core.ChatMessageOuterClass.ChatMessage, tv.twitchbot.common.dto.proto.core.ChatMessageOuterClass.ChatMessage.Builder, tv.twitchbot.common.dto.proto.core.ChatMessageOuterClass.ChatMessageOrBuilder>(
                  getChatMessage(),
                  getParentForChildren(),
                  isClean());
          chatMessage_ = null;
        }
        return chatMessageBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:tv.twitchbot.common.dto.proto.messages.ChatMessageEvent)
    }

    // @@protoc_insertion_point(class_scope:tv.twitchbot.common.dto.proto.messages.ChatMessageEvent)
    private static final tv.twitchbot.common.dto.proto.messages.EventOuterClass.ChatMessageEvent DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new tv.twitchbot.common.dto.proto.messages.EventOuterClass.ChatMessageEvent();
    }

    public static tv.twitchbot.common.dto.proto.messages.EventOuterClass.ChatMessageEvent getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<ChatMessageEvent>
        PARSER = new com.google.protobuf.AbstractParser<ChatMessageEvent>() {
      public ChatMessageEvent parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ChatMessageEvent(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ChatMessageEvent> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ChatMessageEvent> getParserForType() {
      return PARSER;
    }

    public tv.twitchbot.common.dto.proto.messages.EventOuterClass.ChatMessageEvent getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

    public static final int DATA_FIELD_NUMBER = 101;
    /**
     * <code>extend .tv.twitchbot.common.dto.proto.messages.Event { ... }</code>
     */
    public static final
      com.google.protobuf.GeneratedMessage.GeneratedExtension<
        tv.twitchbot.common.dto.proto.messages.EventOuterClass.Event,
        tv.twitchbot.common.dto.proto.messages.EventOuterClass.ChatMessageEvent> data = com.google.protobuf.GeneratedMessage
            .newMessageScopedGeneratedExtension(
          tv.twitchbot.common.dto.proto.messages.EventOuterClass.ChatMessageEvent.getDefaultInstance(),
          0,
          tv.twitchbot.common.dto.proto.messages.EventOuterClass.ChatMessageEvent.class,
          tv.twitchbot.common.dto.proto.messages.EventOuterClass.ChatMessageEvent.getDefaultInstance());
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tv_twitchbot_common_dto_proto_messages_Event_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tv_twitchbot_common_dto_proto_messages_Event_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tv_twitchbot_common_dto_proto_messages_ChatMessageEvent_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tv_twitchbot_common_dto_proto_messages_ChatMessageEvent_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013Event.proto\022&tv.twitchbot.common.dto.p" +
      "roto.messages\032\rMessage.proto\032\021ChatMessag" +
      "e.proto\"\345\001\n\005Event\022E\n\004type\030\001 \002(\01627.tv.twi" +
      "tchbot.common.dto.proto.messages.Event.E" +
      "ventType\"\035\n\tEventType\022\020\n\014CHAT_MESSAGE\020\001*" +
      "\010\010d\020\200\200\200\200\0022l\n\004data\022/.tv.twitchbot.common." +
      "dto.proto.messages.Message\030e \001(\0132-.tv.tw" +
      "itchbot.common.dto.proto.messages.Event\"" +
      "\320\001\n\020ChatMessageEvent\022E\n\014chat_message\030\001 \002" +
      "(\0132/.tv.twitchbot.common.dto.proto.core.",
      "ChatMessage2u\n\004data\022-.tv.twitchbot.commo" +
      "n.dto.proto.messages.Event\030e \001(\01328.tv.tw" +
      "itchbot.common.dto.proto.messages.ChatMe" +
      "ssageEvent"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          tv.twitchbot.common.dto.proto.messages.MessageOuterClass.getDescriptor(),
          tv.twitchbot.common.dto.proto.core.ChatMessageOuterClass.getDescriptor(),
        }, assigner);
    internal_static_tv_twitchbot_common_dto_proto_messages_Event_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tv_twitchbot_common_dto_proto_messages_Event_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tv_twitchbot_common_dto_proto_messages_Event_descriptor,
        new java.lang.String[] { "Type", });
    internal_static_tv_twitchbot_common_dto_proto_messages_ChatMessageEvent_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_tv_twitchbot_common_dto_proto_messages_ChatMessageEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tv_twitchbot_common_dto_proto_messages_ChatMessageEvent_descriptor,
        new java.lang.String[] { "ChatMessage", });
    tv.twitchbot.common.dto.proto.messages.MessageOuterClass.getDescriptor();
    tv.twitchbot.common.dto.proto.core.ChatMessageOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
