//import './polyfills';
// Angular
import '@angular/platform-browser';
import '@angular/platform-browser-dynamic';
import '@angular/core';
import '@angular/common';
import '@angular/router';
// RxJS
import 'rxjs';
import 'rxjs/add/operator/catch';
import 'rxjs/add/operator/map';
import 'rxjs/add/operator/share';
import 'rxjs/add/operator/publishReplay';
import 'rxjs/add/operator/mergeAll';
import 'rxjs/add/operator/first';
import 'rxjs/add/operator/filter';
import 'rxjs/add/operator/find';
import 'rxjs/add/operator/retryWhen';
import 'long';
import 'bytebuffer';
import 'rxjs-websockets';
import 'queueing-subject';
import 'uuid';
// FontAwesome
import '@fortawesome/fontawesome';
import '@fortawesome/fontawesome-free-brands';
import '@fortawesome/fontawesome-pro-regular';
// Bootstrap
import './scss/bootstrap-dashboard/bootstrap-dashboard.scss';
