// Angular
import '@angular/platform-browser';
import '@angular/platform-browser-dynamic';
import '@angular/core';
import '@angular/common';
import '@angular/http';
import '@angular/router';
// RxJS
import 'rxjs';
import 'long';
import 'bytebuffer';
import 'rxjs-websockets';
import 'queueing-subject';
import 'uuid';
// FontAwesome
import '@fortawesome/fontawesome';
import '@fortawesome/fontawesome-free-brands';
import '@fortawesome/fontawesome-pro-regular';
